### ISSUE TITLE
Wrong return code on `cobbler check` failure

### ISSUE THREAD

**Issue by xenlo** [cobbler/cobbler#2475] opened 2020-12-21 17:32 UTC
### Describe the bug

When the command `cobbler check` fails, it prompts correctly error messages but it returns `0` as return value to the shell.
It should be some value higher than zero to indicate that it didn't ended successfully. 

### To Reproduce

1. Generate a typo in the config `/etc/cobbler/modules.conf`
    (for instance like a `module = wroooong_managers.bad`)
2. Then check the config with `cobbler check`
    It has to tells you it failed to load modules
3. Check the return code
    It's zero…

```
cobbler4:~ # cobbler check
Failed to load module for dhcp/module
cobbler4:~ # echo $?
0
```

### Expected behavior
The return code should be higher than zero to indicate to the shell that it didn't end successfully.

### Version

````paste below
cobbler4:~ # cobbler version
Cobbler 3.1.2
  source: ?, ?
  build time: Fri Nov 13 12:00:00 2020
````

**Comment by nodeg** [comment] 2021-04-28 06:10
Duplicate of #1057.

**Closed by nodeg** 2021-04-28 06:10 UTC
Labels: 3.1.2, Bug Report, Good first issue
