### ISSUE TITLE
UEFI does not work.

### ISSUE THREAD

**Issue by asimat** [cobbler/cobbler#2517] opened 2021-01-14 20:15 UTC
As new PCs will no longer come with legacy BIOS, I am trying to get UEFI working. It works fine with our WDS, but not with cobbler.

I have tried version 2.8.5 and v3.2, UEFI does not work. If I copy grubx64.efi from Centos8.3 CD then it boots to grub prompt.

I am using CENTOS 8.3 for my cobbler server, with TFTPD on same server but using a windows DHCP with option 60, 66 & 67 being used which points to Cobbler.

BIOS boot to pxelinux.0 also works fine.

To me it looks like certain folders are missing e.g. chainloader /EFI/centos/grubx64.efi, so as the files cannot be found so grub will do "boot # if it doesn't exist, leave grub and enter shell"

We should prioritize GRUB2 and EFI fix as all new computers are UEFI only.

**Comment by javier-angulo** [comment] 2021-01-15 11:10
Hello @asimat ,UEFI works on v3.2 (at least for me).
grub/grubx64.efi needs to be generated with mkgrub.sh (at /usr/share/cobbler/bin/mkgrub.sh on CentOS).
For that you need to install package grub2-efi-x64-modules
Also, you will need to export GRUB2_MOD_DIR for the script (maybe script has the default path for Suse?):
`# export GRUB2_MOD_DIR="/usr/share/grub"; sh /usr/share/cobbler/bin/mkgrub.sh`

**Comment by dansou901** [comment] 2021-01-15 15:19
^^ I can second that, I also have UEFI via grub and cobbler working fine in our env.

**Comment by SchoolGuy** [comment] 2021-01-16 11:05
I will close this as a duplicate of #1777 (or rather this issue is a subset of what I am trying to do).

@asimat As said UEFI works but the docs are not good and `buildiso` is not able to generate a UEFI Bootable ISO for you. The fact to make this possible will be hard due to the concept of Secure Boot but I will find a way. For only provisioning clients via Cobbler directly stay to the tips from @dansou901 and @javier-angulo !

**Closed by SchoolGuy** 2021-01-16 11:05 UTC

**Comment by hagaluly** [comment] 2021-03-02 16:20
any due date on cobbler UEFI support?
we also have a lot of new servers supporting only UEFI
is there any date upon releasing the fix?
