### ISSUE TITLE
Better UX

### ISSUE THREAD

**Issue by davehodg** [cobbler/cobbler#2330] opened 2020-04-20 10:40 UTC
I'm finding the cobbler user interface clunky and often confusing. Also, the design is so millennial. Any chance we could get (a) really good Ux person(s) to give it a good going over?

**Comment by SchoolGuy** [comment] 2020-04-20 11:42
@davehodg This is already known. So in theory is a duplicate of https://github.com/cobbler/cobbler/issues/1691

Also we know that the current Django Version we are using is EOL. But there is a lack of contributors who have the time to do such a thing currently.

**Comment by SchoolGuy** [comment] 2020-04-20 11:43
You may also find the roadmap interesting in that regard: https://github.com/cobbler/cobbler/wiki/Roadmap-for-Cobbler

**Comment by davehodg** [comment] 2020-04-20 12:40
OK, in that case ignore me. Sounds like upgrading django is way higher up the priority list.

Here's an example. On the edit profiles page, the save/cancel should be bottom right. 

I think the entity relationships could do with clarifying for a n00b.

But equally, you seem to have it all under control. Feel free to close this and move on.

**Comment by SchoolGuy** [comment] 2020-04-20 12:49
Well upgrading Django basically means that we need to redo the UX because what we currently have as an application does not suit the Django structure. We may even need to change the framework if we think that upgrading Django basically is a rewrite of Cobbler. I will leave this one open as a reminder that there is active interest in that. Every input help!

**Comment by davehodg** [comment] 2020-04-20 12:54
Probably worth it.

Is it as big a change as Python 2-3? (Having been bitten by ansible migrating...)

**Comment by SchoolGuy** [comment] 2020-04-20 13:00
I don't know tbh. These days Django really is architected that you have a DB running on the server side. Currently we have no database there by default so we would need to rewrite the persistance layer. Also the models we currently have would need to be changed into "Django-Models" to make use of the benefits Django is offering. The Web frontend needs to be anyway done from scratch as one JS Lib for the Notifications is not maintained anymore. Also it is pretty simple. There are missing a lot of validators missing on various places. So I think it would be a rewrite if we want to take advantage of Django features. If we want to just have "something" as a web frontend, I think a framework change might be better... But this is just a personal opinion.

**Comment by davehodg** [comment] 2020-04-20 13:05
MIght be a case of picking the right framework. I'm just scratching the surface of Flask. After twenty-odd years of Perl on the web. And trust me, they were odd.

Would mandating MySQL/Maria be so bad? SQLite wouldn't be. Few prereqs there.

**Comment by SchoolGuy** [comment] 2020-04-20 13:09
Having a DB was in the early days of Cobbler a decision which was done on purpose because back then everyone was afraid of a database for such a service. There are connectors for mogodb and mysql available for a persistence layer. But they are untested and there is next to no docs for them.

I think if we decide to get rid of the file persistence layer then we could in theory go for Django because then Django does all the database work or at least abstracts a lot of it. And yes I know that Flask exists. I did not look deeper into it so far because I need to focus to get docs/tests and core functionality right. Because even if we redo it in "Django" we do not want to port undocumented, untested and broken code.

**Comment by SchoolGuy** [comment] 2020-05-13 06:57
Future discussions about the web-ui and web-ux should be done now in: https://github.com/cobbler/cobbler/issues/2342

**Closed by SchoolGuy** 2020-05-13 06:57 UTC
Labels: Feature Request, web-interface
