### ISSUE TITLE
Web Interface broken - but easy fix

### ISSUE THREAD

**Issue by asimat** [cobbler/cobbler#2518] opened 2021-01-14 20:24 UTC
I installed v3.2 and the web interface does not work. However I got it working with following two fixes.

replaced `/etc/httpd/conf.d/cobbler_web.conf` with the one from master git https://github.com/cobbler/cobbler/blob/master/config/apache/cobbler_web.conf

then vi `/etc/httpd/conf.d/cobbler_web.conf` and change the following line to:

```
WSGIScriptAlias /cobbler_web /usr/share/cobbler/web/cobbler.wsgi
```

Can we fix this on priority as most users would need the web interface working.

**Comment by dansou901** [comment] 2021-01-15 15:17
I don't think that this will be fixed as the current web interface will be removed in 3.3.0. A new web interface is already being developed but will need more time and I guess it won't be ready for 3.3.0. We will try to make sure that the timeframe for cobbler being without a web interface is as short as possible.

**Comment by SchoolGuy** [comment] 2021-01-16 11:17
@asimat I will fix it for 3.2.1 but you are welcome to open a PR for this as well.

**Comment by nodeg** [comment] 2021-02-16 08:05
@asimat I am trying to reproduce your issue. You said you replaced the `cobbler_web.conf` file from release 3.2.0 with the one from master. The only difference is one [commit](https://github.com/cobbler/cobbler/commits/master/config/apache/cobbler_web.conf) introduced last month.
Here you can see what this commit actually changed:
```diff
diff --git a/config/apache/cobbler_web.conf b/config/apache/cobbler_web.conf
index 0c464638..1996dcc4 100644
--- a/config/apache/cobbler_web.conf
+++ b/config/apache/cobbler_web.conf
@@ -1,10 +1,19 @@
-# This configuration file enables the cobbler web
-# interface (django version)
+# Enable Modules if not already enabled
+<IfModule !wsgi_module>
+    LoadModule wsgi_module /usr/lib64/apache2/mod_wsgi.so
+</IfModule>
+<IfModule !proxy_module>
+    LoadModule wsgi_module /usr/lib64/apache2-prefork/modules/mod_proxy.so
+</IfModule>
+<IfModule !proxy_http_module>
+    LoadModule wsgi_module /usr/lib64/apache2-prefork/mod_proxy_http.so
+</IfModule>
+
+# This configuration file enables the cobbler web interface (django version)
 
 Alias /cobbler_webui_content @@webroot@@/cobbler_webui_content
 
-# Let mod_wsgi know about the location block,
-# so it can access /cobbler_web
+# Let mod_wsgi know about the location block, so it can access /cobbler_web
 <Location /cobbler_web>
     Require all granted
 </Location>
```

The line you edited
> then vi `/etc/httpd/conf.d/cobbler_web.conf` and change the following line to:
> 
> ```
> WSGIScriptAlias /cobbler_web /usr/share/cobbler/web/cobbler.wsgi
> ```
is the same in both versions, so the problem was not solved with that. Maybe it was the part about enabling the modules from the commit mentioned above.

Could you please provide us with more information, for example which GNU/Linux distro do you use with Cobbler?

**Comment by nodeg** [comment] 2021-03-06 20:51
I will close this issue now since we removed the Django webinterface with #2434 for the upcoming version 3.3.0. Furthermore I was not able to reproduce the issue and there is no feedback from the creator of the issue.

**Closed by nodeg** 2021-03-06 20:51 UTC
Labels: 3.2.0, Question, web-interface
