### ISSUE TITLE
Cobbler deletes repo when rename "--newname" parameter is missing

### ISSUE THREAD

**Issue by wsanders** [cobbler/cobbler#1760] opened 2017-02-27 21:38 UTC
This is in version 2.6.11, the version that ships with CentOS 6.8.

Trying to rename a repo, the repo gets delete if the "--newname" parameters is missing:
```bash
$ cobbler repo list
   CentOS_6-epel
   CentOS_6.2-x86_64-updates
   CentOS_6.5-x86_64-updates
...
   CentOS_6.8-x86_64-updates
   CentOS_7-epel
   CentOS_7.2.1511-updates
   centos-7.3.1611-extras
   centos-7.3.1611-updates

$ cobbler repo rename --name=centos-7.3.1611-extras Centos-7.3.1611-extras
exception on server: 'newname'

$ cobbler repo list
   CentOS_6-epel
   CentOS_6.2-x86_64-updates
   CentOS_6.5-x86_64-updates
...
   CentOS_6.8-x86_64-updates
   CentOS_7-epel
   CentOS_7.2.1511-updates
   centos-7.3.1611-updates
```

A "cobbler reposync" doesn't regenerate the repo, although the json file is still present and the repo is still present in /var/www/cobbler.....

**Comment by nodeg** [comment] 2021-03-06 22:10
I was not able to reproduce this on openSUSE Leap 15.2 with git master.

```
$ cobbler version
Cobbler 3.2.1
  source: 0862c327, Sat Mar 6 15:25:00 2021 +0100
  build time: Sat Mar  6 21:37:14 2021

$ cobbler repo list
   test
   test2

$ cobbler repo rename --name=test Test
exception on server: 'newname'

$ cobbler repo list
   test
   test2

$ cobbler repo rename --name=test --newname=Test3
$ cobbler repo list
   Test3
   test2
```

**Comment by SchoolGuy** [comment] 2021-03-07 13:49
Since we were not able to reproduce this, we will close it. If the issue reapers, we will reopen this issue.

**Closed by SchoolGuy** 2021-03-07 13:49 UTC
Labels: 2.6.11, Bug Report, PKG
