### ISSUE TITLE
A PKCS #11 module returned CKR_DEVICE_ERR

### ISSUE THREAD

**Issue by vipulob** [cobbler/cobbler#1816] opened 2017-07-30 11:48 UTC
````
$ cat /etc/redhat-release
CentOS Linux release 7.2.1511 (Core)
````

````
$ cobbler get-loaders
task started: 2017-07-30_165418_get_loaders
task started (id=Download Bootloader Content, time=Sun Jul 30 16:54:18 2017)
running python triggers from /var/lib/cobbler/triggers/task/get_loaders/pre/*
running shell triggers from /var/lib/cobbler/triggers/task/get_loaders/pre/*
shell triggers finished successfully
path /var/lib/cobbler/loaders/README already exists, not overwriting existing content, use --force if you wish to update
downloading https://cobbler.github.io/loaders/COPYING.yaboot to /var/lib/cobbler/loaders/COPYING.yaboot
Exception occured: <class 'urlgrabber.grabber.URLGrabError'>
Exception value: [Errno 14] curl#35 - "A PKCS #11 module returned CKR_DEVICE_ERROR, indicating that a problem has occurred with the token or slot."
Exception Info:
  File "/usr/lib/python2.7/site-packages/cobbler/remote.py", line 85, in run
    rc = self._run(self)
   File "/usr/lib/python2.7/site-packages/cobbler/remote.py", line 182, in runner
    self.remote.api.dlcontent(self.options.get("force", False), self.logger)
   File "/usr/lib/python2.7/site-packages/cobbler/api.py", line 708, in dlcontent
    return grabber.run(force)
   File "/usr/lib/python2.7/site-packages/cobbler/action_dlcontent.py", line 72, in run
    urlgrabber.grabber.urlgrab(src, filename=dst, proxies=proxies)
   File "/usr/lib/python2.7/site-packages/urlgrabber/grabber.py", line 755, in urlgrab
    return default_grabber.urlgrab(url, filename, **kwargs)
   File "/usr/lib/python2.7/site-packages/urlgrabber/grabber.py", line 1201, in urlgrab
    return _run_callback(opts.failfunc, opts)
   File "/usr/lib/python2.7/site-packages/urlgrabber/grabber.py", line 1052, in _run_callback
    return cb(obj)
   File "/usr/lib/python2.7/site-packages/urlgrabber/grabber.py", line 1046, in _do_raise
    raise obj.exception

!!! TASK FAILED !!!
````

**Comment by jmaas** [comment] 2017-10-02 17:52
Can't reproduce. Something with SSL/TLS so it seems.

**Comment by SchoolGuy** [comment] 2020-11-19 15:39
That is not Cobbler related. Thus closing.

**Closed by SchoolGuy** 2020-11-19 15:39 UTC
Labels: Bug Report
