### ISSUE TITLE
cobbler_api: 404 Not Found

### ISSUE THREAD

**Issue by BRVN01** [cobbler/cobbler#2540] opened 2021-02-08 22:37 UTC
### Version

````paste below
Cobbler V3.2.0
````

### Question
I'm trying to compile Cobbler for Debian buster and focal Ubuntu, but I always stop at the same problem.

I'm using this link to compile (https://cobbler.readthedocs.io/en/latest/installation-guide.html#id2).

The message that appears on both systems follows (I am using the most current version). 

```
httpd does not appear to be running and proxying Cobbler, or SELinux is in the way. Original traceback:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/cobbler/cli.py", line 397, in check_setup
    s.ping()
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1109, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1450, in __request
    response = self.__transport.request(
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1153, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1183, in single_request
    raise ProtocolError(
xmlrpc.client.ProtocolError: <ProtocolError for 127.0.0.1:80/cobbler_api: 404 Not Found>
Traceback (most recent call last):
  File "/usr/local/bin/cobbler", line 35, in <module>
    sys.exit(app.main())
  File "/usr/local/lib/python3.8/dist-packages/cobbler/cli.py", line 861, in main
    rc = cli.run(sys.argv)
  File "/usr/local/lib/python3.8/dist-packages/cobbler/cli.py", line 418, in run
    self.token = self.remote.login("", self.shared_secret)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1109, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1450, in __request
    response = self.__transport.request(
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1153, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1183, in single_request
    raise ProtocolError(
xmlrpc.client.ProtocolError: <ProtocolError for 127.0.0.1:80/cobbler_api: 404 Not Found>
```

Would anyone know how to solve?

Thanks!

**Comment by SchoolGuy** [comment] 2021-02-09 16:27
So effectively this means that your Cobbler hasn't started up. The reason why could possibly in `/var/log/cobbler/cobbler.log`. If this file is missing the output of the installation process should be watched closely as it could be that some error is silently ignored...

**Comment by BRVN01** [comment] 2021-02-09 18:42
I'm finding something strange, when I see cobblerd and apache2, both are running.

● cobblerd.service - Cobbler Helper Daemon
     Loaded: loaded (/lib/systemd/system/cobblerd.service; enabled; vendor preset: enabled)
     Active: active (running) since Tue 2021-02-09 18:12:48 UTC; 5s ago
    Process: 1122 ExecStartPost=/usr/bin/touch /usr/share/cobbler/web/cobbler.wsgi (code=exited, status=0/SUCCESS)
   Main PID: 1121 (cobblerd)
      Tasks: 1 (limit: 5678)
     Memory: 30.1M
     CGroup: /system.slice/cobblerd.service
             └─1121 /usr/bin/python3 /usr/bin/cobblerd -F

Feb 09 18:12:48 cloudinit systemd[1]: Starting Cobbler Helper Daemon...
Feb 09 18:12:48 cloudinit systemd[1]: Started Cobbler Helper Daemon.


● apache2.service - The Apache HTTP Server
     Loaded: loaded (/lib/systemd/system/apache2.service; enabled; vendor preset: enabled)
     Active: active (running) since Tue 2021-02-09 16:57:14 UTC; 9min ago
       Docs: https://httpd.apache.org/docs/2.4/
    Process: 631 ExecStart=/usr/sbin/apachectl start (code=exited, status=0/SUCCESS)
   Main PID: 743 (apache2)
      Tasks: 55 (limit: 5678)
     Memory: 20.8M
     CGroup: /system.slice/apache2.service
             ├─743 /usr/sbin/apache2 -k start
             ├─744 /usr/sbin/apache2 -k start
             └─745 /usr/sbin/apache2 -k start

Feb 09 16:57:06 cloudinit systemd[1]: Starting The Apache HTTP Server...
Feb 09 16:57:14 cloudinit apachectl[687]: AH00558: apache2: Could not reliably determine the server's fully qualified domain name,>
Feb 09 16:57:14 cloudinit systemd[1]: Started The Apache HTTP Server.


- Log file:

root@cloudinit:~# cat /var/log/cobbler/cobbler.log 
2021-02-09T18:30:36 - INFO | 11 breeds and 119 OS versions read from the signature file
2021-02-09T18:30:36 - DEBUG | API handle initialized
2021-02-09T18:30:36 - DEBUG | XMLRPC running on 25151



During the compilation I could see so many module import errors that it would be crazy to fix all of them, 
I don't know if this can be fixed by fixing it in a file before compiling.

Below is the compilation of cobbler, it is very large so I left it in a file in my git.
https://github.com/BRVN01/Erros/blob/main/cobbler.output

**Comment by SchoolGuy** [comment] 2021-02-10 07:14
The errors while building you can ignore. This is just the Sphinx autodoc extension which can't find the Logging File Config of Cobbler. I am aware of it and know it is harmless. Fixing this at a later point when we can invest more time in such "false-postives".

**Comment by SchoolGuy** [comment] 2021-02-10 07:15
Since you are on a Debian System... Could it be that armor is in the permissive mode and blocking the communication?

**Comment by BRVN01** [comment] 2021-02-10 13:06
I don't have SELinux, but I can put it on to see if something changes. I'll test.

**Comment by SchoolGuy** [comment] 2021-02-10 19:41
@BRVN01 Apparmor is the equivalent of SELinux on Debian. It is enabled by default. Thus it could be that this is blocking the API calls.

**Comment by BRVN01** [comment] 2021-02-10 22:58
I apologize, I always thought that apparmor is the same as selinux.
I removed the apparmor, but nothing has changed.

Is there no possibility that /cobbler_api does not exist? I didn't find him anywhere.

**Comment by SchoolGuy** [comment] 2021-02-11 05:52
`cobbler_api` is the path in the Apache configuration. Thus it only exists there.

**Comment by tim1670** [comment] 2021-03-04 06:11
I reproduced this problem in Ubuntu20.04lts desktop version. The solution is to create a new apache2 conf-enable folder (it seems to be the name) to correspond to all the soft connections related to the cobbler configuration file in the conf-available folder, and comment according to the log Useless configuration.

**Comment by BRVN01** [comment] 2021-03-07 21:57
I don't know if I did something wrong, but it didn't work.

I created the conf-enable folder, after that included the folder in apache.conf, but it didn't work, 
Can you help me again, please?

**Comment by SchoolGuy** [comment] 2021-03-08 06:17
@BRVN01 Did you do a `a2enconf` for the configuration? Otherwise it won't be active.

**Comment by BRVN01** [comment] 2021-03-08 14:56
Yes, I did. Actually, I created a symbolic link pointing there. 
Now I did it with a2enconf, but it didn't work.

**Comment by tim1670** [comment] 2021-03-13 13:54
In the final analysis, it is an apache configuration problem. Please configure the apache configuration correctly. In addition, this method is only for version 3.2.

**Comment by holmesb** [comment] 2022-01-10 22:52
`ln -sf /etc/apache2/conf-available/cobbler.conf /etc/apache2/conf-enabled/cobbler.conf` 
then restarting apache fixed for me on Ubuntu.

**Comment by SchoolGuy** [comment] 2022-01-15 13:51
Okay since other contributors were happy with the solutions I proposed, I will close this issue now.

**Closed by SchoolGuy** 2022-01-15 13:51 UTC
Labels: Packaging, 3.2.0
