### ISSUE TITLE
SSL errors when downloading files from https://cobbler.github.io

### ISSUE THREAD

**Issue by jaywcarman** [cobbler/cobbler#1888] opened 2018-04-24 10:41 UTC
Running `cobbler get-loaders` fails due to an SSL error:
```
# cobbler get-loaders
task started: 2018-04-24_092015_get_loaders
task started (id=Download Bootloader Content, time=Tue Apr 24 09:20:15 2018)
path /var/lib/cobbler/loaders/README already exists, not overwriting existing content, use --force if you wish to update
path /var/lib/cobbler/loaders/COPYING.elilo already exists, not overwriting existing content, use --force if you wish to update
path /var/lib/cobbler/loaders/COPYING.yaboot already exists, not overwriting existing content, use --force if you wish to update
downloading https://cobbler.github.io/loaders/COPYING.syslinux to /var/lib/cobbler/loaders/COPYING.syslinux
Exception occured: <class 'urlgrabber.grabber.URLGrabError'>
Exception value: [Errno 14] problem making ssl connection
Exception Info:
  File "/usr/local/lib/python2.7/dist-packages/cobbler/remote.py", line 82, in run
    rc = self._run(self)
   File "/usr/local/lib/python2.7/dist-packages/cobbler/remote.py", line 176, in runner
    return self.remote.api.dlcontent(self.options.get("force",False), self.logger)
   File "/usr/local/lib/python2.7/dist-packages/cobbler/api.py", line 735, in dlcontent
    return grabber.run(force)
   File "/usr/local/lib/python2.7/dist-packages/cobbler/action_dlcontent.py", line 73, in run
    urlgrabber.grabber.urlgrab(src, filename=dst, proxies=proxies)
   File "/usr/lib/python2.7/dist-packages/urlgrabber/grabber.py", line 618, in urlgrab
    return default_grabber.urlgrab(url, filename, **kwargs)
   File "/usr/lib/python2.7/dist-packages/urlgrabber/grabber.py", line 982, in urlgrab
    return self._retry(opts, retryfunc, url, filename)
   File "/usr/lib/python2.7/dist-packages/urlgrabber/grabber.py", line 886, in _retry
    r = apply(func, (opts,) + args, {})
   File "/usr/lib/python2.7/dist-packages/urlgrabber/grabber.py", line 968, in retryfunc
    fo = PyCurlFileObject(url, filename, opts)
   File "/usr/lib/python2.7/dist-packages/urlgrabber/grabber.py", line 1063, in __init__
    self._do_open()
   File "/usr/lib/python2.7/dist-packages/urlgrabber/grabber.py", line 1355, in _do_open
    self._do_grab()
   File "/usr/lib/python2.7/dist-packages/urlgrabber/grabber.py", line 1485, in _do_grab
    self._do_perform()
   File "/usr/lib/python2.7/dist-packages/urlgrabber/grabber.py", line 1290, in _do_perform
    raise err

!!! TASK FAILED !!!
```

Running `cobbler signature update` also fails.

If I use non-secure http the downloads are successful. i.e.:
```
diff --git a/cobbler/action_dlcontent.py b/cobbler/action_dlcontent.py
index 73b0de7..73257b7 100644
--- a/cobbler/action_dlcontent.py
+++ b/cobbler/action_dlcontent.py
@@ -46,7 +46,7 @@ class ContentDownloader:
         they can still source their cross-arch bootloader content manually.
         """
 
-        content_server = "https://cobbler.github.io/loaders"
+        content_server = "http://cobbler.github.io/loaders"
         dest = "/var/lib/cobbler/loaders"
 
         files = (
```

**Comment by spikebike** [comment] 2018-05-02 00:01
Same thing happens for me with cobbler signatures update, and the above mentioned fix doesn't fix it.

**Comment by jaywcarman** [comment] 2018-05-02 10:49
@spikebike  The signatures URL is in 'cobbler/settings.py':
```
diff --git a/cobbler/settings.py b/cobbler/settings.py
index cf55be3..16bd0ba 100644
--- a/cobbler/settings.py
+++ b/cobbler/settings.py
@@ -127,7 +127,7 @@ DEFAULTS = {
     "server"                              : ["127.0.0.1","str"],
     "sign_puppet_certs_automatically"     : [0,"bool"],
     "signature_path"                      : ["/var/lib/cobbler/distro_signatures.json","str"],
-    "signature_url"                       : ["https://cobbler.github.io/signatures/2.8.x/latest.json","str"],
+    "signature_url"                       : ["http://cobbler.github.io/signatures/2.8.x/latest.json","str"],
     "snippetsdir"                         : ["/var/lib/cobbler/snippets","str"],
     "template_remote_kickstarts"          : [0,"bool"],
     "virt_auto_boot"                      : [0,"bool"],
```

**Comment by jaywcarman** [comment] 2018-05-02 12:04
Recently GitHub dropped support for TLSv1/TLSv1.1 (https://githubengineering.com/crypto-deprecation-notice/). I bet the `urlgrabber` module is using an old SSL/TLS library (I'm running in an Ubuntu 14.04 LXC container).

**Comment by jmaas** [comment] 2018-05-03 19:35
Reverting back to http does not seem to be the right approach.

**Comment by spikebike** [comment] 2018-05-04 00:32
Even with that I get:
root@nas-2-1:/var/lib/cobbler# cobbler signature update
task started: 2018-05-03_173030_sigupdate
task started (id=Updating Signatures, time=Thu May  3 17:30:30 2018
Exception occured: <class 'urlgrabber.grabber.URLGrabError'>
Exception value: [Errno 14] problem making ssl connection

This might be specific to ubuntu-14.04, I'll see if I can find/upgrade url grabber to something newer.

My goal is to upgrade everything to 18.04, but of course I wanted cobbler to work first so I can reinstall everything.

**Comment by spikebike** [comment] 2018-05-04 00:39
Hrmpf, I ran "pip install urlgrabber --upgrade", which resulted in urlgrabber-3.10.2 being installed.  But when I test:
```
>>> from urlgrabber.grabber import URLGrabber
>>> g = URLGrabber()
>>> data = g.urlread("https://cobbler.github.io/signatures/2.8.x/latest.json")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/urlgrabber/grabber.py", line 1236, in urlread
    s = self._retry(opts, retryfunc, url, limit)
  File "/usr/local/lib/python2.7/dist-packages/urlgrabber/grabber.py", line 1086, in _retry
    r = apply(func, (opts,) + args, {})
  File "/usr/local/lib/python2.7/dist-packages/urlgrabber/grabber.py", line 1219, in retryfunc
    fo = PyCurlFileObject(url, filename=None, opts=opts)
  File "/usr/local/lib/python2.7/dist-packages/urlgrabber/grabber.py", line 1284, in __init__
    self._do_open()
  File "/usr/local/lib/python2.7/dist-packages/urlgrabber/grabber.py", line 1629, in _do_open
    self._do_grab()
  File "/usr/local/lib/python2.7/dist-packages/urlgrabber/grabber.py", line 1767, in _do_grab
    raise e
urlgrabber.grabber.URLGrabError: [Errno 14] curl#35 - "gnutls_handshake() failed: Handshake failed"
```

**Comment by spikebike** [comment] 2018-05-04 01:16
I tried replacing URL grabber and api.py with:
```
-import urlgrabber
+import requests

-           response = urlgrabber.grabber.urlopen(self.settings().signature_url, proxies=proxies)
-           sigjson = response.read()

+            r=requests.get(self.settings().signature_url)
+            sigjson = r.contents
```

Sadly I couldn't get it to work, it seems to still be finding urlgrabber in api.py, even though when I grep that file I see no hint of urlgrabber.

**Comment by jaywcarman** [comment] 2018-05-04 02:10
Looks like Ubuntu 14.04 defaults to python 2.7.6. Python 2 versions older than 2.7.9 lack SNI support (https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings). Tomorrow I'll try using a newer Python 2 version along with urlgrabber-3.10.2 and see if SSL works.

**Comment by jmaas** [comment] 2018-05-04 06:57
I cant reproduce on Fedora 28.

**Comment by spikebike** [comment] 2018-05-04 20:50
@jaywcarman Bingo, good find.  I upgraded python, reinstalled cobbler, and:
```
root@nas-2-1:/share/apps/src/cobbler-2.8.2# cobbler signature update
task started: 2018-05-04_134936_sigupdate
task started (id=Updating Signatures, time=Fri May  4 13:49:36 2018)
Successfully got file from https://cobbler.github.io/signatures/2.8.x/latest.json
*** TASK COMPLETE ***
root@nas-2-1:/share/apps/src/cobbler-2.8.2# 
```

**Comment by jmaas** [comment] 2018-05-05 07:08
Nice find, now we know some features don't work on 4 year old Ubuntu :)
I'm not considering this to be a Cobbler bug. Closing this issue.

**Closed by jmaas** 2018-05-05 07:08 UTC
