### ISSUE TITLE
cobbler api service unable to access setting file

### ISSUE THREAD

**Issue by geliwei** [cobbler/cobbler#3202] opened 2022-07-21 13:34 UTC
### Describe the bug

when I type "curl http://localhost/cblr/svc/op/setting"

I  got 

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>500 Internal Server Error</title>
</head><body>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error or
misconfiguration and was unable to complete
your request.</p>
<p>Please contact the server administrator at 
 root@localhost to inform them of the time this error occurred,
 and the actions you performed just before this error.</p>
<p>More information about this error may be available
in the server error log.</p>
</body></html>

I check /var/log/httpd/error_log
I found svc/service.py report a exception

PermissionError: [Errno 13] Permission denied: '/etc/cobbler/settings_20220721_21-03-27.yaml'

### Steps to reproduce

1. install cobbler-3.3.2-2
2. setup
3. curl http://localhost/cblr/svc/op/setting

### Cobbler version

````paste below
````

### Cobbler log

````paste below
````

**Comment by SchoolGuy** [comment] 2022-07-21 13:42
This is a duplicate of #2967. It was fixed in #3020 and was backported to 3.3.3 with #3084.

**Closed by SchoolGuy** 2022-07-21 13:42 UTC
Labels: Bug Report

**Comment by bruncsak** [comment] 2022-11-18 14:16
@SchoolGuy , is it possible to backport the fix to 3.3.2 also?

**Comment by SchoolGuy** [comment] 2022-11-18 14:32
@bruncsak Well since 3.3.3 contains the patch that was already done. A re-release of 3.3.2 is not really in question.
