### ISSUE TITLE
AlmaLinux 9.3 Minimal import error

### ISSUE THREAD

**Issue by 3XC1T3D** [cobbler/cobbler#3531] opened 2023-12-20 11:42 UTC
### Describe the bug

```
cobbler import --path=/mnt/cdrom --name=AlmaLinux-9 --arch=x86_64
task started: 2023-12-20_123749_import
task started (id=Media import, time=Wed Dec 20 12:37:49 2023)
running python triggers from /var/lib/cobbler/triggers/task/import/pre/*
running shell triggers from /var/lib/cobbler/triggers/task/import/pre/*
shell triggers finished successfully
import_tree; ['/mnt/cdrom', 'AlmaLinux-9', None, None, None]
importing from a network location, running rsync to fetch the files first
running: rsync -a  '/mnt/cdrom/' /var/www/cobbler/distro_mirror/AlmaLinux-9-x86_64 --progress
received on stdout: sending incremental file list
received on stderr: 
Found a candidate signature: breed=suse, version=opensuse15.0
Found a candidate signature: breed=suse, version=opensuse15.1
Found a candidate signature: breed=suse, version=opensuse15.2
Found a candidate signature: breed=suse, version=opensuse15.3
Found a candidate signature: breed=suse, version=opensuse15.4
Found a candidate signature: breed=suse, version=sles15generic
No signature matched in /var/www/cobbler/distro_mirror/AlmaLinux-9-x86_64
Exception occurred: <class 'cobbler.cexceptions.CX'>
Exception value: 'No signature matched in /var/www/cobbler/distro_mirror/AlmaLinux-9-x86_64'
Exception Info:
!!! TASK FAILED !!!
```

### Steps to reproduce

1. prepare distro for import
2. cobbler import --path=/mnt/cdrom --name=AlmaLinux-9 --arch=x86_64
3. receive error

### Expected behavior

Expected cobbler to finish import process so that the pxe boot profile could be used.

### Cobbler version

````
Cobbler 3.3.3
  source: ?, ?
  build time: Tue Jun 14 00:00:00 2022

````

### Operating system

AlmaLinux release 9.3 (Shamrock Pampas Cat)

### Cobbler log

````
         32,768  18%  123.55kB/s    0:00:01  
        179,456 100%  671.46kB/s    0:00:00 (xfr#999, to-chk=5/1014)
isolinux/libutil.c32

         23,508 100%   87.96kB/s    0:00:00  
         23,508 100%   87.96kB/s    0:00:00 (xfr#1000, to-chk=4/1014)
isolinux/memtest

         32,768  21%  120.30kB/s    0:00:01  
        153,868 100%  562.78kB/s    0:00:00 (xfr#1001, to-chk=3/1014)
isolinux/splash.png

            186 100%    0.68kB/s    0:00:00  
            186 100%    0.68kB/s    0:00:00 (xfr#1002, to-chk=2/1014)
isolinux/vesamenu.c32

         26,696 100%   97.64kB/s    0:00:00  
         26,696 100%   97.64kB/s    0:00:00 (xfr#1003, to-chk=1/1014)
isolinux/vmlinuz

         32,768   0%  119.85kB/s    0:01:51  
     13,372,728 100%   31.11MB/s    0:00:00 (xfr#1004, to-chk=0/1014)

[2023-12-20_123749_import] 2023-12-20T12:38:13 - DEBUG | received on stderr: 
[2023-12-20_123749_import] 2023-12-20T12:38:13 - DEBUG | Found a candidate signature: breed=suse, version=opensuse15.0
[2023-12-20_123749_import] 2023-12-20T12:38:13 - DEBUG | Found a candidate signature: breed=suse, version=opensuse15.1
[2023-12-20_123749_import] 2023-12-20T12:38:13 - DEBUG | Found a candidate signature: breed=suse, version=opensuse15.2
[2023-12-20_123749_import] 2023-12-20T12:38:13 - DEBUG | Found a candidate signature: breed=suse, version=opensuse15.3
[2023-12-20_123749_import] 2023-12-20T12:38:13 - DEBUG | Found a candidate signature: breed=suse, version=opensuse15.4
[2023-12-20_123749_import] 2023-12-20T12:38:13 - DEBUG | Found a candidate signature: breed=suse, version=sles15generic
[2023-12-20_123749_import] 2023-12-20T12:38:13 - ERROR | No signature matched in /var/www/cobbler/distro_mirror/AlmaLinux-9-x86_64
[2023-12-20_123749_import] 2023-12-20T12:38:13 - INFO | Exception occurred: <class 'cobbler.cexceptions.CX'>
[2023-12-20_123749_import] 2023-12-20T12:38:13 - INFO | Exception value: 'No signature matched in /var/www/cobbler/distro_mirror/AlmaLinux-9-x86_64'
[2023-12-20_123749_import] 2023-12-20T12:38:13 - INFO | Exception Info:
  File "/usr/lib/python3.9/site-packages/cobbler/remote.py", line 99, in run
    rc = self._run(self)

  File "/usr/lib/python3.9/site-packages/cobbler/remote.py", line 305, in runner
    self.remote.api.import_tree(

  File "/usr/lib/python3.9/site-packages/cobbler/api.py", line 1759, in import_tree
    import_module.run(path, mirror_name, network_root, autoinstall_file, arch, breed, os_version)

  File "/usr/lib/python3.9/site-packages/cobbler/modules/managers/import_signatures.py", line 194, in run
    raise CX(error_msg)

[2023-12-20_123749_import] 2023-12-20T12:38:13 - ERROR | ### TASK FAILED ###

````

**Comment by 3XC1T3D** [comment] 2023-12-20 12:33
Seems that the import fails only if i am using the **Minimal** ISO from AlmaLinux 9.3.

When i am using the **Full** DVD ISO from AlmaLinux 9.3, the import is successful.

Maybe the Minimal ISO is missing some Information?

**Comment by 3XC1T3D** [comment] 2023-12-20 13:02
I changed following lines in the **/var/lib/cobbler/distro_signatures.json** file from:
```
      "rhel9": {
        "signatures": [
          "BaseOS"
        ],
```
to
```
      "rhel9": {
        "signatures": [
          "BaseOS",
          "Minimal"
        ],
```
and the import of the Minimal ISO worked

**Comment by SchoolGuy** [comment] 2023-12-31 13:59
This is a duplicate of #2623

**Closed by SchoolGuy** 2023-12-31 13:59 UTC
Labels: Bug Report, 3.3.3
