### ISSUE TITLE
Debian 8.3 & 8.4 issue

### ISSUE THREAD

**Issue by magditawfik** [cobbler/cobbler#1649] opened 2016-04-05 15:26 UTC
I have cobbler server 2.6.11 running with no issues I can install debian 7 , Centos 7 ESXi 5.1  and 5.5 no issues
I'm getting error MSG from Debian 8.3 & 8.4 that no CD-ROM detected  ,  and got Msg to install the CD-ROM  driver from removable media!!!!
can someone help please 

Thank you 
Mag

**Comment by magditawfik** [comment] 2016-04-05 16:07
I have remembered that i have copied netboot linux & initrd from netboot CDROM



Thank you
M

**Comment by nacc** [comment] 2016-04-11 21:54
Does that mean this issue is fixed once you used the correct kernel and initrd?

**Comment by jmaas** [comment] 2016-05-10 06:21
Perhaps we can improve the signature so that the correct kernel/initrd are copied over....

**Comment by nacc** [comment] 2016-05-10 06:26
Right, the issue is that the appropriate netboot kernel and initrd are not on the ISO. I guess we could special case the signature based import and d/l the right files from the standard location for Debian and Ubuntu?

**Comment by jmaas** [comment] 2016-05-15 19:48
Hmm, perhaps we should only support the netinst ISO then.

**Comment by jmaas** [comment] 2016-10-19 06:37
I dont like the idea of special casing for media that are not intended to be used in a PXE environment.
Downloading installer components may sound nice but doesnt work for those people whose systems are not connected to the Internet.

**Comment by jmaas** [comment] 2016-10-19 06:39
Closing this issue, people should use the correct media. I just tested with debian 8.6.0 (DVD1).

**Closed by jmaas** 2016-10-19 06:39 UTC
Labels: bug_report
