### ISSUE TITLE
Unable to import CentOS 8 in Cobbler 3.0.1 on CentOS 8

### ISSUE THREAD

**Issue by YvesDegauquier** [cobbler/cobbler#2195] opened 2019-11-07 19:25 UTC
I compiled from the latest version on CentOS 8 the version 3.0.1 of Cobbler.
I did a full rsync of CentOS 8 (kickstart).
Impossible to import into Cobbler:
````
[root@infra01 cobbler]# cobbler import --name=centos-8-x86_64 --available-as=http://infra01.degauquier.home/repo/centos/8/kickstart --path=/repo/centos/8/kickstart
task started: 2019-11-07_201224_import
task started (id=Media import, time=Thu Nov  7 20:12:24 2019)
running python triggers from /var/lib/cobbler/triggers/task/import/pre/*
running shell triggers from /var/lib/cobbler/triggers/task/import/pre/*
shell triggers finished successfully
Found a candidate signature: breed=redhat, version=rhel6
Found a candidate signature: breed=redhat, version=rhel7
Found a candidate signature: breed=redhat, version=ovz7
Found a candidate signature: breed=redhat, version=fedora16
Found a candidate signature: breed=redhat, version=fedora17
Found a candidate signature: breed=redhat, version=fedora18
Found a candidate signature: breed=redhat, version=fedora19
Found a candidate signature: breed=redhat, version=fedora20
Found a candidate signature: breed=redhat, version=fedora21
Found a candidate signature: breed=redhat, version=fedora22
Found a candidate signature: breed=redhat, version=fedora23
Found a candidate signature: breed=redhat, version=fedora24
Found a candidate signature: breed=redhat, version=fedora25
Found a candidate signature: breed=redhat, version=fedora26
Found a candidate signature: breed=redhat, version=fedora27
Found a candidate signature: breed=redhat, version=fedora28
Found a candidate signature: breed=redhat, version=fedora29
Found a candidate signature: breed=redhat, version=fedora30
Found a candidate signature: breed=redhat, version=cloudlinux6
Found a candidate signature: breed=suse, version=opensuse15.0
Found a candidate signature: breed=suse, version=opensuse15.1
Found a candidate signature: breed=suse, version=sles15generic
No signature matched in /var/www/cobbler/distro_mirror/centos-8-x86_64
Exception occured: <class 'cobbler.cexceptions.CX'>
Exception value: 'No signature matched in /var/www/cobbler/distro_mirror/centos-8-x86_64'
Exception Info:
  File "/usr/lib/python3.6/site-packages/cobbler/remote.py", line 84, in run
    rc = self._run(self)

  File "/usr/lib/python3.6/site-packages/cobbler/remote.py", line 231, in runner
    self.logger

  File "/usr/lib/python3.6/site-packages/cobbler/api.py", line 862, in import_tree
    import_module.run(path, mirror_name, network_root, autoinstall_file, arch, breed, os_version)

  File "/usr/lib/python3.6/site-packages/cobbler/modules/managers/import_signatures.py", line 171, in run
    raise CX(error_msg)

!!! TASK FAILED !!!
[root@infra01 cobbler]# ls /repo/centos/8/kickstart
EFI  images  isolinux  media.repo  Packages  repodata
[root@infra01 cobbler]# find /var/www/cobbler/distro_mirror/centos-8-x86_64
/var/www/cobbler/distro_mirror/centos-8-x86_64
/var/www/cobbler/distro_mirror/centos-8-x86_64/Packages
/var/www/cobbler/distro_mirror/centos-8-x86_64/Packages/centos-release-8.0-0.1905.0.9.el8.x86_64.rpm
/var/www/cobbler/distro_mirror/centos-8-x86_64/Packages/kernel-4.18.0-80.el8.x86_64.rpm
/var/www/cobbler/distro_mirror/centos-8-x86_64/Packages/kernel-abi-whitelists-4.18.0-80.el8.noarch.rpm
/var/www/cobbler/distro_mirror/centos-8-x86_64/Packages/kernel-core-4.18.0-80.el8.x86_64.rpm
/var/www/cobbler/distro_mirror/centos-8-x86_64/Packages/kernel-cross-headers-4.18.0-80.el8.x86_64.rpm
/var/www/cobbler/distro_mirror/centos-8-x86_64/Packages/kernel-modules-4.18.0-80.el8.x86_64.rpm
/var/www/cobbler/distro_mirror/centos-8-x86_64/Packages/kernel-modules-extra-4.18.0-80.el8.x86_64.rpm
/var/www/cobbler/distro_mirror/centos-8-x86_64/Packages/kernel-tools-4.18.0-80.el8.x86_64.rpm
/var/www/cobbler/distro_mirror/centos-8-x86_64/Packages/kernel-tools-libs-4.18.0-80.el8.x86_64.rpm
/var/www/cobbler/distro_mirror/centos-8-x86_64/images
/var/www/cobbler/distro_mirror/centos-8-x86_64/images/pxeboot
/var/www/cobbler/distro_mirror/centos-8-x86_64/images/pxeboot/initrd.img
/var/www/cobbler/distro_mirror/centos-8-x86_64/images/pxeboot/vmlinuz
/var/www/cobbler/distro_mirror/centos-8-x86_64/isolinux
/var/www/cobbler/distro_mirror/centos-8-x86_64/isolinux/boot.msg
/var/www/cobbler/distro_mirror/centos-8-x86_64/isolinux/grub.conf
/var/www/cobbler/distro_mirror/centos-8-x86_64/isolinux/initrd.img
/var/www/cobbler/distro_mirror/centos-8-x86_64/isolinux/isolinux.bin
/var/www/cobbler/distro_mirror/centos-8-x86_64/isolinux/isolinux.cfg
/var/www/cobbler/distro_mirror/centos-8-x86_64/isolinux/ldlinux.c32
/var/www/cobbler/distro_mirror/centos-8-x86_64/isolinux/libcom32.c32
/var/www/cobbler/distro_mirror/centos-8-x86_64/isolinux/libutil.c32
/var/www/cobbler/distro_mirror/centos-8-x86_64/isolinux/memtest
/var/www/cobbler/distro_mirror/centos-8-x86_64/isolinux/splash.png
/var/www/cobbler/distro_mirror/centos-8-x86_64/isolinux/vesamenu.c32
/var/www/cobbler/distro_mirror/centos-8-x86_64/isolinux/vmlinuz
````

**Comment by rbberger** [comment] 2019-11-11 13:59
Looks to me like the RHEL8 signature should also check for "Packages", not just BaseOS (which is on the ISO)

**Comment by Hyper200** [comment] 2020-12-22 15:39
Hi there,

Is there a work around available for this?

Having the done a cobbler signature update

cobbler signature update
task started: 2020-12-22_153759_sigupdate
task started (id=Updating Signatures, time=Tue Dec 22 15:37:59 2020)
Successfully got file from https://cobbler.github.io/signatures/2.8.x/latest.json
*** TASK COMPLETE ***


We get this on the import:

cobbler import --path=/media/isomount/ --name="CentOS-8.3-x86_64" --arch=x86_64
task started: 2020-12-22_153834_import
task started (id=Media import, time=Tue Dec 22 15:38:34 2020)
Found a candidate signature: breed=suse, version=sles15generic
Found a candidate signature: breed=suse, version=opensuse15.0
Found a candidate signature: breed=suse, version=opensuse15.1
Found a candidate signature: breed=redhat, version=rhel8
No signature matched in /var/www/cobbler/ks_mirror/CentOS-8.3-x86_64
!!! TASK FAILED !!!

Thanks,

cobbler-web-2.8.5

**Comment by SchoolGuy** [comment] 2020-12-26 12:44
@Hyper200 So far sadly no. But I will try to fix is for the next release 3.2.1!

**Comment by kpiche** [comment] 2020-12-29 19:36
In CentOS 8.3 the centos-release RPM was renamed to centos-linux-release.  After adding "centos-linux" to the rhel8 version_file expression in distro_signatures.json the import worked.

**Comment by asimat** [comment] 2021-01-14 20:41
For general users, this means do: 

vi /var/lib/cobbler/distro_signatures.json

Makes the line version_file look as follow: 

"version_file": "(redhat|sl|slf|centos|centos-linux|centos-stream|oraclelinux|vzlinux)-release-(?!notes)([\\w]*-)*8[\\.-]+(.*)\\.rpm",

**Comment by razorsedge** [comment] 2021-02-15 15:10
And then restart cobblerd.
`service cobblerd restart`

**Comment by Hyper200** [comment] 2021-02-15 15:18
This worked thanks !

**Comment by nodeg** [comment] 2021-02-18 10:45
> `"version_file": "(redhat|sl|slf|centos|centos-linux|centos-stream|oraclelinux|vzlinux)-release-(?!notes)([\\w]*-)*8[\\.-]+(.*)\\.rpm",`

The only change here is the missing `almalinux` entry. I tested importing CentOS 8 with your suggested change and without it on the `master` branch and was **not** able to reproduce the issue. In both cases the import was successful unless you take a netinstall/live image instead of a full DVD image.

I used the following 2 images from [here](https://ftp.fau.de/centos/8.3.2011/isos/x86_64/) to test this:
```
CentOS-8.3.2011-x86_64-boot.iso          2020-11-18 22:01  683M  
CentOS-8.3.2011-x86_64-dvd1.iso          2020-11-18 22:43  8.6G  
```
When using the `boot` image I ran into the following error while importing:

```shell
$ cobbler import --name=centos-8-x86_64_boot --path /home/dom/Downloads/centos                                                                                           
task started: 2021-02-18_112400_import                                                                                                                                   
task started (id=Media import, time=Thu Feb 18 11:24:00 2021)                                                                                                            
running python triggers from /var/lib/cobbler/triggers/task/import/pre/*                                                                                                 
running shell triggers from /var/lib/cobbler/triggers/task/import/pre/*                                                                                                  
shell triggers finished successfully                                                                                                                                     
Found a candidate signature: breed=suse, version=opensuse15generic                                                                                                       
Found a candidate signature: breed=suse, version=sles15generic                                                                                                           
Exception occurred: <class 'KeyError'>                                                                                                                                   
Exception value: 'signatures'                                                                                                                                            
Exception Info:                                                                     
  File "/usr/local/lib/python3.8/site-packages/cobbler/remote.py", line 98, in run                                                                                       
    rc = self._run(self)                                                                                                                                                 
                                                                                                                                                                         
  File "/usr/local/lib/python3.8/site-packages/cobbler/remote.py", line 296, in runner                                                                                   
    self.remote.api.import_tree(                                                    
                                          
  File "/usr/local/lib/python3.8/site-packages/cobbler/api.py", line 1504, in import_tree                                                                                
    import_module.run(path, mirror_name, network_root, autoinstall_file, arch, breed, os_version)                                                                        
                                          
  File "/usr/local/lib/python3.8/site-packages/cobbler/modules/managers/import_signatures.py", line 191, in run                                                          
    self.signature = self.scan_signatures()                                         
                                                                                    
  File "/usr/local/lib/python3.8/site-packages/cobbler/modules/managers/import_signatures.py", line 224, in scan_signatures                                              
    for sig in sigdata["breeds"][breed][version]["signatures"]:                     
                                          
!!! TASK FAILED !!!
```
This is 'normal' since the [quickinstall documentation](https://cobbler.readthedocs.io/en/latest/quickstart-guide.html#download-an-iso-image) states you must use the full DVD version when importing images.

When using the `dvd1` image the import succeeds:

```shell
$ cobbler import --name=centos-8-x86_64_alma --path /home/dom/Downloads/centos 
task started: 2021-02-18_112723_import
task started (id=Media import, time=Thu Feb 18 11:27:23 2021)
running python triggers from /var/lib/cobbler/triggers/task/import/pre/*
running shell triggers from /var/lib/cobbler/triggers/task/import/pre/*
shell triggers finished successfully
Found a candidate signature: breed=redhat, version=rhel8
Found a matching signature: breed=redhat, version=rhel8
Adding distros from path /srv/www/cobbler/distro_mirror/centos-8-x86_64_alma:
creating new distro: centos-8_alma-x86_64
trying symlink: /srv/www/cobbler/distro_mirror/centos-8-x86_64_alma -> /srv/www/cobbler/links/centos-8_alma-x86_64
creating new profile: centos-8_alma-x86_64
associating repos
checking for rsync repo(s)
checking for rhn repo(s)
checking for yum repo(s)
starting descent into /srv/www/cobbler/distro_mirror/centos-8-x86_64_alma for centos-8_alma-x86_64
processing repo at : /srv/www/cobbler/distro_mirror/centos-8-x86_64_alma/AppStream
need to process repo/comps: /srv/www/cobbler/distro_mirror/centos-8-x86_64_alma/AppStream
looking for /srv/www/cobbler/distro_mirror/centos-8-x86_64_alma/AppStream/repodata/*comps*.xml
Keeping repodata as-is :/srv/www/cobbler/distro_mirror/centos-8-x86_64_alma/AppStream/repodata
processing repo at : /srv/www/cobbler/distro_mirror/centos-8-x86_64_alma/BaseOS
need to process repo/comps: /srv/www/cobbler/distro_mirror/centos-8-x86_64_alma/BaseOS
looking for /srv/www/cobbler/distro_mirror/centos-8-x86_64_alma/BaseOS/repodata/*comps*.xml
Keeping repodata as-is :/srv/www/cobbler/distro_mirror/centos-8-x86_64_alma/BaseOS/repodata
*** TASK COMPLETE ***
```

I close this issue since the import works on the newer Cobbler version.

**Closed by nodeg** 2021-02-18 10:45 UTC
Labels: 3.0.1, Bug Report, ISO
