### ISSUE TITLE
Building cobbler via pip install fails

### ISSUE THREAD

**Issue by nodeg** [cobbler/cobbler#2412] opened 2020-09-17 08:10 UTC
### Describe the bug

Building the cobbler package via `pip` fails. 

### To Reproduce

1. Clone git repository
2. Create a new virtualenv
3. Install required packages and build cobbler via `pip install .`

### Expected behavior

The build should be successful.

### Version
The most recent git version.

### Additional context
````bash
$ pip install .            
Processing /home/dom/test/cobbler
    ERROR: Command errored out with exit status 1:
     command: /home/dom/test/cobbler/cobbler/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-ifgastb7/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-ifgastb7/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-eh235bqq
         cwd: /tmp/pip-req-build-ifgastb7/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-ifgastb7/setup.py", line 19, in <module>
        from sphinx.setup_command import BuildDoc
    ModuleNotFoundError: No module named 'sphinx'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
````
After installing `sphinx` with `pip install sphinx` the output is the following:

```bash
$ pip install .     
Processing /home/dom/test/cobbler
    ERROR: Command errored out with exit status 1:
     command: /home/dom/test/cobbler/cobbler/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-1psr03eg/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-1psr03eg/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-bmn1r60r
         cwd: /tmp/pip-req-build-1psr03eg/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-1psr03eg/setup.py", line 22, in <module>
        from coverage import Coverage
    ModuleNotFoundError: No module named 'coverage'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
After installing `coverage` with `pip install coverage`, cobbler was successfully built.

```bash
$ pip install .
(...)
Building wheels for collected packages: cobbler
  Building wheel for cobbler (setup.py) ... done
  Created wheel for cobbler: filename=cobbler-3.2.0-py3-none-any.whl size=721152 sha256=f87fc3401ed1c372f0636badaf5bdcd97780a1119261d4f7f9658ea14ae4b37c
  Stored in directory: /tmp/pip-ephem-wheel-cache-7be40114/wheels/9d/af/82/749f930a855e3501b10ae27fd583f9749aa65f041a8919d2d8
Successfully built cobbler
Installing collected packages: mod-wsgi, pyyaml, simplejson, netaddr, Cheetah3, asgiref, sqlparse, Django, pymongo, distro, pyasn1, ldap3, dnspython, tornado, cobbler
Successfully installed Cheetah3-3.2.5 Django-3.1.1 asgiref-3.2.10 cobbler-3.2.0 distro-1.5.0 dnspython-2.0.0 ldap3-2.8.1 mod-wsgi-4.7.1 netaddr-0.8.0 pyasn1-0.4.8 pymongo-3.1
1.0 pyyaml-5.3.1 simplejson-3.17.2 sqlparse-0.3.1 tornado-6.0.4
```

According to the [setuptools documentation](https://setuptools.readthedocs.io/en/latest/setuptools.html#new-and-changed-setup-keywords) 
> Using setup_requires is discouraged in favor of PEP-518.

so maybe it is advisable to swtich from `setup_requires` to the proposals made in [PEP 518](https://www.python.org/dev/peps/pep-0518).

When looking into the `setup.py` file

https://github.com/cobbler/cobbler/blob/e6e029a986a6bf5112087c8eedcf6912a3574a5d/setup.py#L507-L512

you see that those 2 packages are listed inside `setup_requires`.

**Comment by dansou901** [comment] 2020-09-17 08:26
So everything under setup_requires should be moved to install_requires instead, right? And setup_requires can be removed afterwards.

**Comment by nodeg** [comment] 2020-09-17 09:00
That has to be discussed. If moving everything from `setup_requires` to `install_requires` is the right way, is not mine to they since I am not that familiar with Cobbler itself but I think we should keep the distinction between both of them.
According to PEP 518, [PEP 517](https://www.python.org/dev/peps/pep-0517) and the [pip documentation](https://pip.pypa.io/en/stable/reference/pip/?highlight=pyproject%20toml#pep-517-and-518-support) regarding both, one solution would be to use a `pyproject.toml` file for the setup/build process with e.g. the following content:

```toml
[build-system]
requires = ["coverage", "distro", "setuptools", "sphinx"]
```
and get rid of the `setup_requires` part in `setup.py`.

**Comment by SchoolGuy** [comment] 2020-09-21 07:47
After our discussion in this issue and the related PR (#2414) we came to the conclusion that this is not doable currently. So this is not a bug but rather a known regression. For the corresponding feature request please see #2415 

We will close this issue when our this problem is documented in our rtd and we have some adjustments in the makefile for a temporary fix.

**Comment by SchoolGuy** [comment] 2020-11-19 08:11
I will close this Bug, since we have a Feature Request for it, namely #2415 .

For now this behavior is intended. The patch for solving it is included in the Feature Request.

**Closed by SchoolGuy** 2020-11-19 08:11 UTC
Labels: Bug Report
