### ISSUE TITLE
Locale setting for Ubuntu 16.04 and 18.04 with the default sample.seed

### ISSUE THREAD

**Issue by logicodex** [cobbler/cobbler#2017] opened 2019-02-06 22:53 UTC
I made a custom preseed file based on the default sample.seed file using exactly the same locale settings, but unlike using the sample.seed, I cannot skip the "choosing a language" step without using a kernel parameter (e.g. locale=en_US) with my preseed file.

What makes the default sample.seed file to skip the step of choosing a language during the Ubuntu 16.04 and 18.04 installation?

Environment:
Cobbler 2.8.4

**Comment by kwizart** [comment] 2019-06-03 12:43
That's a good question and a good workaround.

Maybe if one cannot figure out a sane way to set the appropriate locale using preseed, maybe it would be better to document the fix/workaround in the default.preseed.

Does it works the same with current Debian ?
Would you be able to submit a patch with the appropriate documentation in the default.preseed ?

**Comment by SchoolGuy** [comment] 2019-06-18 07:37
@logicodex This issue seems not to be related with cobbler or am I missing something here? If I am correct then I would suggest we close this one.

**Comment by kwizart** [comment] 2019-06-18 07:50
I think it relates to cobbler because if the correct way to do unattended install with Debian is to specify the locale with a kernel parameter, then  maybe it's possible for cobbler to add this parameter by default with any Debian system.

With that said, it could also be a documentation issue. In that case, it should also be possible to modify the default.seed to mention that.

**Comment by SchoolGuy** [comment] 2019-06-18 08:11
@kwizart Well we support as far as I tested it that you can set kernel parameters to a system/profile/distro, so this should already be possible. But I will see what we can do about this one.

**Comment by kwizart** [comment] 2019-06-18 08:59
Well, I'm not sure to reproduce the need of a locale=en_US in cmdline.
It could be that the default profile is missing the following directive: (tested with my french defaults).
d-i keyboard-configuration/xkb-keymap select fr

**Comment by SchoolGuy** [comment] 2019-07-14 14:14
Since your PR is merged I will close this one.

**Closed by SchoolGuy** 2019-07-14 14:14 UTC
Labels: PXE, doc_report
