### ISSUE TITLE
Check /etc/cobbler/modules.conf"

### ISSUE THREAD

**Issue by spikebike** [cobbler/cobbler#1751] opened 2017-02-10 09:13 UTC
I'm building from source and I tried release26, release28, and master on ubuntu-16.04.

In all cases when I try to run cobblerd:
root@nas-10-1:/usr/local# /usr/local/bin/cobblerd
Traceback (most recent call last):
  File "/usr/local/bin/cobblerd", line 76, in main
    api = cobbler_api.CobblerAPI(is_cobblerd=True)
  File "/usr/local/lib/python2.7/dist-packages/cobbler/api.py", line 120, in __init__
    self.deserialize()
  File "/usr/local/lib/python2.7/dist-packages/cobbler/api.py", line 903, in deserialize
    return self._collection_mgr.deserialize()
  File "/usr/local/lib/python2.7/dist-packages/cobbler/collection_manager.py", line 193, in deserialize
    raise CX("serializer: error loading collection %s: %s. Check /etc/cobbler/modules.conf" % (collection.collection_type(), e))
CX: "serializer: error loading collection settings: 'Failed to load module for serializers/settings'. Check /etc/cobbler/modules.conf"

**Comment by jmaas** [comment] 2017-02-19 07:19
Hi, this is a known issue.. the workaround: 

```
ln -s /usr/local/lib/python2.7/dist-packages/cobbler /usr/lib/python2.7/dist-packages
```

It's also documented in: http://cobbler.github.io/manuals/2.8.0/2/3_-_Installing_From_Source.html

But this should be fixed properly. 

Anyone have an idea what the root cause is?

**Comment by jmaas** [comment] 2017-02-19 07:43
The root cause seems to be in `cobbler/module_loader.py`, has to do with the way how cobbler loads modules.

**Comment by jmaas** [comment] 2017-02-19 09:03
This seems to work, need to test some more.
```
#plib = distutils.sysconfig.get_python_lib()
#mod_path="%s/cobbler/modules" % plib
#sys.path.insert(0, mod_path)
#sys.path.insert(1, "%s/cobbler" % plib)
import cobbler
mod_path = os.path.join(os.path.abspath(os.path.dirname(cobbler.__file__)), 'modules')
```

**Comment by jmaas** [comment] 2017-02-19 15:47
Need to backport to release28

**Closed** 2017-02-19 18:37 UTC
Labels: bug_report

**Comment by spikebike** [comment] 2018-02-27 02:53
Just tried compiling from source again with the release28, 2.9 changed quite a bit and there doesn't seem to be many docs.

Still get the same problem, even with:
oot@nas-2-0:~/src/cobbler# ls -al /usr/lib/python2.7/dist-packages/cobbler
lrwxrwxrwx 1 root root 46 Feb 26 17:37 /usr/lib/python2.7/dist-packages/cobbler -> /usr/local/lib/python2.7/dist-packages/cobbler
root@nas-2-0:~/src/cobbler# /usr/local/bin/cobblerd 
Traceback (most recent call last):
  File "/usr/local/bin/cobblerd", line 75, in main
    api = cobbler_api.BootAPI(is_cobblerd=True)
  File "/usr/local/lib/python2.7/dist-packages/cobbler/api.py", line 119, in __init__
    self.deserialize()
  File "/usr/local/lib/python2.7/dist-packages/cobbler/api.py", line 953, in deserialize
    return self._config.deserialize()
  File "/usr/local/lib/python2.7/dist-packages/cobbler/config.py", line 262, in deserialize
    raise CX("serializer: error loading collection %s. Check /etc/cobbler/modules.conf" % item.collection_type())
CX: 'serializer: error loading collection profile. Check /etc/cobbler/modules.conf'
root@nas-2-0:~/src/cobbler#
