### ISSUE TITLE
No matching signature for VMware vSphere 2016 (ESXi 6.5)

### ISSUE THREAD

**Issue by kkemnitz** [cobbler/cobbler#1671] opened 2016-05-20 13:24 UTC
I am attempting to add the latest BETA build for VMware vSphere 2016 (ESXi 6.5) to Cobbler, and although we have created a code snippet in the distros_signatures.json file, it does not match when attempting to import. Previous VMware vSphere 2016 (ESXi 6.5) BETA builds have been added successfully, but beginning with build 3869359, this has been unsuccessful.

Code snippet added to distros_signatures.json:
"esxi65": {
    "signatures":["tboot.b00"],
    "version_file":"s\.v00",
    "version_file_regex":"^._ESXi 6\.5\.(._)build-([\d]+)._$",
    "kernel_arch":"tools\.t00",
    "kernel_arch_regex":"^._(x86_64)._$",
    "supported_arches":["x86_64"],
    "supported_repo_breeds":[],
    "kernel_file":"mboot\.c32",
    "initrd_file":"imgpayld\.tgz",
    "isolinux_ok":false,
    "default_kickstart":"/var/lib/cobbler/kickstarts/sample_esxi6.ks",
    "kernel_options":"",
    "kernel_options_post":"",
    "template_files":"/etc/cobbler/pxe/bootcfg_esxi65.template=$local_img_path/cobbler-boot.cfg",
    "boot_files":["_.*"]
   }

Failure being seen during import:
cobbler import --name=esxi6.5-beta-3869359-051816-inbox --path=/mnt/kkemnitz --kickstart=/var/lib/cobbler/kickstarts/esxi65.cfg
task started: 2016-05-20_075141_import
task started (id=Media import, time=Fri May 20 07:51:41 2016)
Found a candidate signature: breed=vmware, version=esxi65
running: /usr/bin/file /var/www/cobbler/ks_mirror/esxi6.5-beta-3869359-051816-inbox/s.v00
received on stdout: /var/www/cobbler/ks_mirror/esxi6.5-beta-3869359-051816-inbox/s.v00: gzip compressed data, was "vmvisor-sys.vxz-psigned", from Unix, last modified: Tue May 10 12:04:52 2016

received on stderr:
Found a candidate signature: breed=vmware, version=esxi51
running: /usr/bin/file /var/www/cobbler/ks_mirror/esxi6.5-beta-3869359-051816-inbox/s.v00
received on stdout: /var/www/cobbler/ks_mirror/esxi6.5-beta-3869359-051816-inbox/s.v00: gzip compressed data, was "vmvisor-sys.vxz-psigned", from Unix, last modified: Tue May 10 12:04:52 2016

received on stderr:
Found a candidate signature: breed=vmware, version=esxi61
running: /usr/bin/file /var/www/cobbler/ks_mirror/esxi6.5-beta-3869359-051816-inbox/s.v00
received on stdout: /var/www/cobbler/ks_mirror/esxi6.5-beta-3869359-051816-inbox/s.v00: gzip compressed data, was "vmvisor-sys.vxz-psigned", from Unix, last modified: Tue May 10 12:04:52 2016

received on stderr:
Found a candidate signature: breed=vmware, version=esxi60
running: /usr/bin/file /var/www/cobbler/ks_mirror/esxi6.5-beta-3869359-051816-inbox/s.v00
received on stdout: /var/www/cobbler/ks_mirror/esxi6.5-beta-3869359-051816-inbox/s.v00: gzip compressed data, was "vmvisor-sys.vxz-psigned", from Unix, last modified: Tue May 10 12:04:52 2016

received on stderr:
Found a candidate signature: breed=vmware, version=esxi5
running: /usr/bin/file /var/www/cobbler/ks_mirror/esxi6.5-beta-3869359-051816-inbox/s.v00
received on stdout: /var/www/cobbler/ks_mirror/esxi6.5-beta-3869359-051816-inbox/s.v00: gzip compressed data, was "vmvisor-sys.vxz-psigned", from Unix, last modified: Tue May 10 12:04:52 2016

received on stderr:
Found a candidate signature: breed=vmware, version=esxi55
running: /usr/bin/file /var/www/cobbler/ks_mirror/esxi6.5-beta-3869359-051816-inbox/s.v00
received on stdout: /var/www/cobbler/ks_mirror/esxi6.5-beta-3869359-051816-inbox/s.v00: gzip compressed data, was "vmvisor-sys.vxz-psigned", from Unix, last modified: Tue May 10 12:04:52 2016

received on stderr:
No signature matched in /var/www/cobbler/ks_mirror/esxi6.5-beta-3869359-051816-inbox
!!! TASK FAILED !!!

**Comment by kkemnitz** [comment] 2016-06-15 23:04
Any suggestions?

**Comment by bms** [comment] 2016-06-16 02:04
I know from getting XenServer to import that Cobbler can't cope if the files required to match a signature are spread across multiple directories.

**Comment by kkemnitz** [comment] 2016-09-07 15:21
How did you work around that with XenServer, @bms?

**Comment by bms** [comment] 2016-09-24 12:31
See gist: https://gist.github.com/bms/eb7c18bbe22d1302e4a92c59b1ef5f41

**Comment by ujnzxw** [comment] 2017-02-24 01:51
Hi @kkemnitz ,
did you have a successful import with  @bms 's gist?

**Comment by smulrine** [comment] 2017-03-14 10:10
The problem is actually that the format of s.v00 has changed. In earlier versions of ESXi it was a gzipped tar file, which Cobbler could extract on the fly and scan for the version_file_regex string. s.v00 is now a gzipped xz-compressed file. Cobbler performs one level of decompression, and the resulting .xz file contains no recognisable text strings.

I would suggest using vmware-esx-base-osl.txt as the version_file instead:
    "version_file":"vmware-esx-base-osl\\.txt",
    "version_file_regex":"^ESXi v6\\.5\\.0.*$",

**Comment by rgold73** [comment] 2017-06-02 12:49
This issue was opened a year ago and still seems unresolved. I obtained latest.json from http://cobbler.github.com/signatures/latest.json to update distro_signatures.json in /var/lib/cobbler and still no entry for esxi65. Looked at the gist provided by bms and jmaas but I don't see how that matches up with default /manage_import_signatures.py.  If this in addition?  I do see filename of manage_import_signatures.py2016-06-03. Just trying to clarify if this file is in addition to or replacement for default /manage_import_signatures.py. Given the time that has passed since this issue was reported. Why hasn't a signature for esxi65 been added to distro_signatures.json? Why hasn't manage_import_signatures.py itself been updated? Have these changes been resolved in cobbler 2.8.1.
Any idea it usually takes for new cobbler versions to make their way to EPEL?

**Comment by cdubbm** [comment] 2017-06-06 06:06
the gist did not help me at all. the "solution" proposed by smulrine did work a bit better, with a different regex. 

"version_file_regex":"^VMware ESXi 6\\.5.*$",

**Comment by jmaas** [comment] 2017-06-25 13:43
I've got it working locally with the help of the gist provided by @smulrine 
I will commit a signature, pxe template and kickstart ASAP

**Comment by jmaas** [comment] 2017-06-25 18:36
i've just pushed a diff to the release28 branch.
feedback much appreciated!

**Closed** 2017-09-10 09:34 UTC
