### ISSUE TITLE
Sync fails during writing PXE file

### ISSUE THREAD

**Issue by heroin-moose** [cobbler/cobbler#2680] opened 2021-06-22 21:31 UTC
### Describe the bug

`cobbler sync` fails with the following error if some of my systems have
bootloaders set to "pxe":

```
$ cobbler sync
...
Exception occurred: <class 'AttributeError'>
Exception value: 'NoneType' object has no attribute 'to_dict'
Exception Info:
!!! TASK FAILED !!!
```

### Steps to reproduce

1. Create a x86\_64 distro with bootloader "pxe"
2. Create a profile with bootloader "pxe"
3. Create an OS with bootloader "pxe"
4. Run cobbler sync

### Expected behavior

The command should not fail.

### Cobbler version

````paste below
Cobbler 3.2.1
  source: ?, ?
  build time: Tue Jun 22 15:41:34 2021
````

### Operating system

CentOS 8.

### Cobbler log

````paste below
[2021-06-22_212727_sync] 2021-06-22T21:27:28 - INFO | find_items; ['']
[2021-06-22_212727_sync] 2021-06-22T21:27:28 - INFO | find_items; ['distro']
[2021-06-22_212727_sync] 2021-06-22T21:27:28 - INFO | find_items; ['profile']
[2021-06-22_212727_sync] 2021-06-22T21:27:28 - INFO | find_items; ['system']
[2021-06-22_212727_sync] 2021-06-22T21:27:28 - INFO | find_items; ['repo']
[2021-06-22_212727_sync] 2021-06-22T21:27:28 - INFO | find_items; ['image']
[2021-06-22_212727_sync] 2021-06-22T21:27:28 - INFO | find_items; ['mgmtclass']
[2021-06-22_212727_sync] 2021-06-22T21:27:28 - INFO | find_items; ['package']
[2021-06-22_212727_sync] 2021-06-22T21:27:28 - INFO | find_items; ['file']
[2021-06-22_212727_sync] 2021-06-22T21:27:28 - INFO | find_items; ['menu']
[2021-06-22_212727_sync] 2021-06-22T21:27:28 - INFO | Exception occurred: <class 'AttributeError'>
[2021-06-22_212727_sync] 2021-06-22T21:27:28 - INFO | Exception value: 'NoneType' object has no attribute 'to_dict'
[2021-06-22_212727_sync] 2021-06-22T21:27:28 - INFO | Exception Info:
  File "/usr/lib/python3.6/site-packages/cobbler/remote.py", line 96, in run
    rc = self._run(self)

  File "/usr/lib/python3.6/site-packages/cobbler/remote.py", line 212, in runner
    self.remote.api.sync(self.options.get("verbose", False), what=what)

  File "/usr/lib/python3.6/site-packages/cobbler/api.py", line 1379, in sync
    sync_obj.run()

  File "/usr/lib/python3.6/site-packages/cobbler/actions/sync.py", line 144, in run
    self.tftpd.sync(self.verbose)

  File "/usr/lib/python3.6/site-packages/cobbler/modules/managers/in_tftpd.py", line 177, in sync
    menu_items = self.tftpgen.get_menu_items()

  File "/usr/lib/python3.6/site-packages/cobbler/tftpgen.py", line 367, in get_menu_items
    return self.get_menu_level(None, arch)

  File "/usr/lib/python3.6/site-packages/cobbler/tftpgen.py", line 549, in get_menu_level
    self.get_profiles_menu(menu, metadata, arch)

  File "/usr/lib/python3.6/site-packages/cobbler/tftpgen.py", line 449, in get_profiles_menu
    image=None, format=boot_loader)

  File "/usr/lib/python3.6/site-packages/cobbler/tftpgen.py", line 673, in write_pxe_file
    self.build_kernel(metadata, system, profile, distro, image, format)

  File "/usr/lib/python3.6/site-packages/cobbler/tftpgen.py", line 755, in build_kernel
    blended = utils.blender(self.api, True, profile)

  File "/usr/lib/python3.6/site-packages/cobbler/utils.py", line 612, in blender
    results["children"][key] = api_handle.find_items("", name=key, return_list=False).to_dict()

[2021-06-22_212727_sync] 2021-06-22T21:27:28 - ERROR | ### TASK FAILED ###
````

**Comment by heroin-moose** [comment] 2021-06-22 21:59
I suspect that this may relate to #2681, but I am not sure yet.

**Comment by SchoolGuy** [comment] 2021-06-23 07:22
Arghhh I tested that case and it is still bugged. I believe I needs to debug that deeper...

**Comment by SchoolGuy** [comment] 2021-06-23 07:24
That is happening due to the fact that I rewrote how children and parents are resolved. This means at this point we need to look a child up and now we do this with a not exisiting one which means the children dict is not consistent or I havn't added a correct skip condition (e.g. when there are no children for an object).

**Comment by SchoolGuy** [comment] 2021-06-23 09:22
Okay the code in question is https://github.com/cobbler/cobbler/blob/998e3f5ab9c386615a58db2f0e3e4f62166bf08b/cobbler/utils.py#L608-L612

To my understanding the child should never be `None` since we get the list of children from the item directly. Thus I believe the root cause is that a child is wrongfully in another part of the code.

**Comment by SchoolGuy** [comment] 2021-06-23 09:27
I believe to find the root cause we need to check the following things:

- Items: Does the children Setter and Getter work as intended.
- Collections: Does adding a child object (e.g. profile) work in relation to if it gets added to the parent item.
- If above gives no result:
  - API: Do we have side effects when editing an object?
  - Remote: Do we have side effects from xapi object edit for example maybe?

**Comment by SchoolGuy** [comment] 2021-06-23 09:33
Okay I found a possible candidate: In the file `collection.py` is the child added but it never gets removed in the specific other collections.

**Comment by SchoolGuy** [comment] 2021-06-27 08:38
I can't reproduce this at all but even worse I don't get any config files for any bootloader configs at all... My steps were the following (taken from bash history):

- `docker run -it --rm --name cobbler-dev -v $PWD:/code -v /mnt:/mnt cobbler-dev`
- `./docker/develop/scripts/setup-supervisor.sh`
- `cobbler import --name=opensuse153 --arch=x86_64 --path=/mnt`
- `cobbler system add --name=test --profile=opensuse153-x86_64 --mac=01:02:03:04:05:0`
- `cobbler sync --systems=test`

Result:

```
12bdd2eeb0c4:/code # ls -alh /srv/tftpboot/grub/system
total 8.0K
drwxr-xr-x 2 root root 4.0K Jun 27 08:26 .
drwxr-xr-x 4 root root 4.0K Jun 27 08:26 ..
```

This of course is then not a PXE based distro/profile but a Grub based but I still don't get any results. I tried to set the bootloader to PXE after the import but also the `pxelinux.cfg` directory stays empty...

**Comment by heroin-moose** [comment] 2021-06-27 08:41
You have to enable netboot for the system.

**Comment by SchoolGuy** [comment] 2021-06-27 09:04
Okay when not setting a bootloader on the system it gets not inherited by the distro. This needs to be fixed aswell.

**Comment by SchoolGuy** [comment] 2021-06-27 09:05
Okay now with `--netboot-enabled=1` and manually set bootloaders, I am able to reproduce this.

**Comment by heroin-moose** [comment] 2021-06-27 09:06
You do? I can't anymore xD

**Comment by SchoolGuy** [comment] 2021-06-27 09:28
Okay so I can't reproduce above original stacktrace. My comment was referring to the stacktrace in the Gitter Chat

```
exception on server: 'Error with system "" - not all boot_loaders are supported (given: "[\'ipxe\', \'pxe\', \'grub\']"; supported:"[]")'
```

This is actually not a bug but a behavior change. If you do a 

```
cobbler system edit --name=test --boot-loaders="<<inherit>>"
```

for example the inheritance to the profile is working again. I believe that this will be a usability problem in many other places, so I think we need to improve this situation before the release because most people won't read the docs to actually understand this. What also doesn't help is the misleading error message.

**Comment by SchoolGuy** [comment] 2021-06-27 09:29
I will close this issue because noone is able to reproduce it anymore, the discussion about the improvements we can do in the related PR or in another issue.

**Closed by SchoolGuy** 2021-06-27 09:29 UTC
Labels: Bug Report, master
