### ISSUE TITLE
exception on server: '_BindManager' object has no attribute 'write_dns_files'

### ISSUE THREAD

**Issue by mdepot** [cobbler/cobbler#3157] opened 2022-06-13 16:19 UTC
### Describe the bug

Cobbler 3.3.2 calls a function that doesn't exist.

### Steps to reproduce

cobbler system add --name=test --profile=rocky8.6-x86_64
exception on server: '_BindManager' object has no attribute 'write_dns_files'

### Cobbler version

````
cobbler --version
Cobbler 3.3.2
  source: ?, ?
  build time: Wed May  4 01:38:10 2022
````

### Operating system

Rocky 8.6 + EPEL

### Cobbler log

```
[Thread-39] 2022-06-13T11:49:27 - INFO | Writing template files for test
[Thread-39] 2022-06-13T11:49:27 - INFO | generating PXE menu structure
[Thread-39] 2022-06-13T11:49:27 - INFO | rendering DHCP files
[Thread-39] 2022-06-13T11:49:27 - INFO | generating /etc/dhcp/dhcpd.conf
[Thread-39] 2022-06-13T11:49:27 - INFO | rendering DNS files
[Thread-39] 2022-06-13T11:49:27 - INFO | Exception occurred: <class 'AttributeError'>
[Thread-39] 2022-06-13T11:49:27 - INFO | Exception value: '_BindManager' object has no attribute 'write_dns_files'
[Thread-39] 2022-06-13T11:49:27 - INFO | Exception Info:
  File "/usr/lib/python3.6/site-packages/cobbler/remote.py", line 3640, in _dispatch
    return method_handle(*params)

  File "/usr/lib/python3.6/site-packages/cobbler/remote.py", line 2047, in xapi_object_edit
    self.save_item(object_type, handle, token)

  File "/usr/lib/python3.6/site-packages/cobbler/remote.py", line 2102, in save_item
    self.api.add_item(what, obj)

  File "/usr/lib/python3.6/site-packages/cobbler/api.py", line 774, in add_item
    self.get_items(what).add(ref, check_for_duplicate_names=check_for_duplicate_names, save=save)

  File "/usr/lib/python3.6/site-packages/cobbler/cobbler_collections/collection.py", line 409, in add
    self.api.sync_systems(systems=[ref.name])

  File "/usr/lib/python3.6/site-packages/cobbler/api.py", line 1396, in sync_systems
    sync_obj.run_sync_systems(systems)

  File "/usr/lib/python3.6/site-packages/cobbler/actions/sync.py", line 105, in run_sync_systems
    self.dns.write_dns_files()
```

### Additional information

Perhaps should be calling self.dns.write_configs() instead of self.dns.write_dns_files()
```
# lines 102-105 in sync.py
if self.settings.manage_dns:
    self.logger.info("rendering DNS files")
    self.dns.regen_hosts()
    self.dns.write_dns_files()
```

**Comment by SchoolGuy** [comment] 2022-06-14 06:58
This is a duplicate of #2984, was fixed in #2990 for `main` / 3.4.0 and backported in #3049 for 3.3.3.

**Closed by SchoolGuy** 2022-06-14 06:58 UTC
Labels: Bug Report, 3.3.2
