### ISSUE TITLE
cobblerd does no start with error "Error with distro ... - kernel '...' not found"

### ISSUE THREAD

**Issue by bruncsak** [cobbler/cobbler#2854] opened 2021-12-08 15:56 UTC
### Describe the bug

Cobblerd at startup gives the following error in the log, and fails to start:

````
systemd[1]: Starting Cobbler Helper Daemon...
systemd[1]: Started Cobbler Helper Daemon.
cobblerd[412678]: Traceback (most recent call last):
cobblerd[412678]:  File "/usr/lib/python3.6/site-packages/cobbler/cobbler_collections/manager.py", line 199, in deserialize
cobblerd[412678]:    serializer.deserialize(collection)
cobblerd[412678]:  File "/usr/lib/python3.6/site-packages/cobbler/serializer.py", line 129, in deserialize
cobblerd[412678]:    storage_module.deserialize(collection, topological)
cobblerd[412678]:  File "/usr/lib/python3.6/site-packages/cobbler/modules/serializers/file.py", line 160, in deserialize
cobblerd[412678]:    collection.from_list(datastruct)
cobblerd[412678]:  File "/usr/lib/python3.6/site-packages/cobbler/cobbler_collections/collection.py", line 200, in from_list
cobblerd[412678]:    self.add(item)
cobblerd[412678]:  File "/usr/lib/python3.6/site-packages/cobbler/cobbler_collections/collection.py", line 339, in add
cobblerd[412678]:    ref.check_if_valid()
cobblerd[412678]:  File "/usr/lib/python3.6/site-packages/cobbler/items/distro.py", line 147, in check_if_valid
cobblerd[412678]:    raise CX("Error with distro %s - kernel '%s' not found" % (self.name, self.kernel))
cobblerd[412678]: cobbler.cexceptions.CX: "Error with distro CentOS-8.4.2105-kickstart-aarch64 - kernel '/var/www/html/mirror/centos/8.4.2105/BaseOS/aarch64/kickstart/images/pxeboot/vmlinuz' not found"
cobblerd[412678]: The above exception was the direct cause of the following exception:
cobblerd[412678]: Traceback (most recent call last):
cobblerd[412678]:  File "/usr/bin/cobblerd", line 75, in main
cobblerd[412678]:    api = cobbler_api.CobblerAPI(is_cobblerd=True)
cobblerd[412678]:  File "/usr/lib/python3.6/site-packages/cobbler/api.py", line 102, in __init__
cobblerd[412678]:    self.deserialize()
cobblerd[412678]:  File "/usr/lib/python3.6/site-packages/cobbler/api.py", line 1528, in deserialize
cobblerd[412678]:    return self._collection_mgr.deserialize()
cobblerd[412678]:  File "/usr/lib/python3.6/site-packages/cobbler/cobbler_collections/manager.py", line 202, in deserialize
cobblerd[412678]:    % (collection.collection_type(), e)) from e
cobblerd[412678]: cobbler.cexceptions.CX: 'serializer: error loading collection distro: "Error with distro CentOS-8.4.2105-kickstart-aarch64 - kernel \'/var/www/html/mirror/centos/8.4.2105/BaseOS/aarch64/kickstart/images/pxeboot/vmlinuz\' not found". Check /etc/cobbler/modules.conf'
systemd[1]: cobblerd.service: Succeeded.
````
That is probably consistency check for availability of the referred files in the configuration.

### Steps to reproduce

At the time CentOS 8.4.2105 was available, the configuration was consistent. However, minor upgrade came out (8.5.2111) and the files of the previous minor release were removed from the repository. That made the configuration inconsistent.

### Expected behavior

Print error message in the log about the inconsistency, but do not exit at start-up. It is not possible to fix the inconsistency with the cobbler command any more since the cobbler daemon is not running.

### Cobbler version

From `EPEL`:
`cobbler-3.2.2-4.module_el8+13419+741870f6.noarch`

### Operating system

CentOS 8 Stream

**Comment by SchoolGuy** [comment] 2021-12-08 17:08
Duplicate of #2413

**Closed** 2021-12-08 17:08 UTC
Labels: Bug Report
