### ISSUE TITLE
$tree variable not set automatically after importing Rocky 8.7 ISO (v3.3.3 RPMs compiled on Rocky 8)

### ISSUE THREAD

**Issue by bug-catcher-fk-github** [cobbler/cobbler#3275] opened 2022-11-21 13:12 UTC
### Describe the bug

After importing a Rocky 8.7 ISO via the instructions in the official Quickstart guide, the `$tree` variable is not set, which later causes Kickstart installations to entirely fail.

It has to be manually set with:

    # cobbler distro edit  \
    --name="rocky8_7-x86_64"  \
    --autoinstall-meta="tree=http://@@http_server@@/cblr/links/rocky8_7-x86_64/"

### Steps to reproduce

1. Install official dependencies & compile v3.3.3 RPMs on RHEL 8, then install
2. Import distro as in Quickstart guide
3. `$tree` variable is not set in new profile

### Expected behavior

It is suppose to set the `$tree` variable within the new profile that is created, when the import is finished.

### Cobbler version

v3.3.3

### Operating system

Rocky 8.7 (both compiled and installed with)

**Comment by SchoolGuy** [comment] 2023-04-23 15:12
I hit this too during the tests for #3326. I will try to take care of this.

**Comment by SchoolGuy** [comment] 2023-04-23 18:30
Okay this is more complicated to test then thought since inside a container `mount` doesn't work. I will need to push this back a bit as I have a workaround and I want to focus on getting the open PRs merged.

**Comment by SchoolGuy** [comment] 2023-10-29 11:26
I will close this as a duplicate of #3417

**Closed by SchoolGuy** 2023-10-29 11:26 UTC
Labels: Bug Report, 3.3.3
