### ISSUE TITLE
Centos 7 and RHEL 7 PXE Installing fail

### ISSUE THREAD

**Issue by christiangda** [cobbler/cobbler#1477] opened 2015-05-21 14:04 UTC
When PXEing RHEL 7 from Cobbler 2.6.7 my host would load all the way to dracut, at which point I got the dreaded /dev/root error.

```
[   84.985068] dracut Warning: Unable to process initqueue
dracut Warning: Unable to process initqueue  
[   84.985892] dracut Warning: /dev/root does not exist
dracut Warning: /dev/root does not exist

Dropping to debug shell.

dracut:/# _  
```

Cobbler Tested: 

```
Name        : cobbler
Arch        : noarch
Version     : 2.6.8
  and
Name        : cobbler
Arch        : noarch
Version     : 2.6.7
```

I have the problem described here and used his solution and this do the work!

Here is describe the problem and solution: https://blog.vladionescu.com/pxe-installing-rhel-7-from-cobbler-2-6/

Thanks to Vlad Ionescu for his job and his blog!.

**Comment by robert-xiong** [comment] 2015-05-26 05:53
can give the capture of the boot option detail? Thanks very much..

**Comment by christiangda** [comment] 2015-05-26 08:18
Taken from: https://blog.vladionescu.com/pxe-installing-rhel-7-from-cobbler-2-6/

Adding the following to my RHEL 7 Distro's Kernel Options (kopts) allowed RHEL 7 to successfully PXE! The blank ksdevice= overrides Cobbler's blunder, and inst.repo makes the rest of dracut happy.
```
ksdevice= inst.repo=http://11.11.11.11/cblr/ks_mirror/RHEL-7-Workstation-x86_64  
```

Replace 11.11.11.11 with you Cobbler server's IP address, and the rest of the path should point to where you imported your Distro.

and taken from my cobbler server:
```
[root@osprovisioner ~]# cobbler distro report

Name                           : CentOS-7.0-1406-x86_64-NetInstall-x86_64
Architecture                   : x86_64
TFTP Boot Files                : {}
Breed                          : redhat
Comment                        : 
Fetchable Files                : {}
Initrd                         : /var/www/cobbler/ks_mirror/CentOS-7.0-1406-x86_64-NetInstall-x86_64/images/pxeboot/initrd.img
Kernel                         : /var/www/cobbler/ks_mirror/CentOS-7.0-1406-x86_64-NetInstall-x86_64/images/pxeboot/vmlinuz
Kernel Options                 : {'ksdevice': '', 'inst.repo': 'http://10.9.11.210/cblr/ks_mirror/CentOS-7.0-1406-x86_64-NetInstall-x86_64/'}
Kernel Options (Post Install)  : {}
Kickstart Metadata             : {'tree': 'http://@@http_server@@/cblr/links/CentOS-7.0-1406-x86_64-NetInstall-x86_64'}
Management Classes             : []
OS Version                     : rhel7
Owners                         : ['admin']
Red Hat Management Key         : <<inherit>>
Red Hat Management Server      : <<inherit>>
Template Files                 : {}
```

**Comment by robert-xiong** [comment] 2015-05-26 09:47
It still not working.I am so sad .
![ca1](https://cloud.githubusercontent.com/assets/12604007/7809766/33177130-03cf-11e5-8095-1396be36a955.png)
![ca2](https://cloud.githubusercontent.com/assets/12604007/7809765/32dcf190-03cf-11e5-9bc0-af8686185af9.png)
could be any other mistake?

**Comment by christiangda** [comment] 2015-05-26 09:53
Did you check the link put in "Kernel Options", this  exists?,  what is your error?

My provisioner server is Centos 7, if you read https://blog.vladionescu.com/pxe-installing-rhel-7-from-cobbler-2-6/, it'll do the job

**Comment by robert-xiong** [comment] 2015-05-26 10:01
yes,I have checked it,do exist.And the error :
![error](https://cloud.githubusercontent.com/assets/12604007/7809998/10f23200-03d1-11e5-9d61-ba6d96976cbf.png)
and the Addr is working
![web](https://cloud.githubusercontent.com/assets/12604007/7810012/2cc83f9c-03d1-11e5-9525-86df46f67653.png)

**Comment by christiangda** [comment] 2015-05-26 11:08
Did you do?
```
cobbler sync
```
check the file in 
```
#NOTE: With your mac system
/var/lib/tftpboot/pxelinux.cfg/01-c4-6e-1f-00-99-ec
```
and its content will be something like
```
LABEL CentOS-7.0-1406-x86_64-NetInstall-x86_64
        kernel /images/CentOS-7.0-1406-x86_64-NetInstall-x86_64/vmlinuz
        MENU LABEL CentOS-7.0-1406-x86_64-NetInstall-x86_64
        append initrd=/images/CentOS-7.0-1406-x86_64-NetInstall-x86_64/initrd.img ksdevice lang=  inst.repo=http://10.9.11.210/cblr/ks_mirror/CentOS-7.0-1406-x86_64-NetInstall-x86_64/ kssendmac text  ks=http://10.9.11.210/cblr/svc/op/ks/profile/CentOS-7.0-1406-x86_64-NetInstall-x86_64
        ipappend 2
```
The new kernel params will be there!

**Comment by robert-xiong** [comment] 2015-05-27 01:30
yes,I have do "cobbler sync" , but no file named by my mac address .just a file named "default".In this file, I find the content
[root@localhost /]# vi /var/lib/tftpboot/pxelinux.cfg/default
DEFAULT menu
PROMPT 0
MENU TITLE Cobbler | http://www.cobblerd.org/
TIMEOUT 200
TOTALTIMEOUT 6000
ONTIMEOUT local

LABEL local
        MENU LABEL (local)
        MENU DEFAULT
        LOCALBOOT -1

LABEL CentOS-7.0-x86_64
        kernel /images/CentOS-7.0-x86_64/vmlinuz
        MENU LABEL CentOS-7.0-x86_64
        append initrd=/images/CentOS-7.0-x86_64/initrd.img ksdevice lang=  inst.repo=http://192.168.71.101/cblr/links/CentOS-7.0-x86_64/ text kssendmac  ks=http://192.168.71.101/cblr/svc/op/ks/profile/CentOS-7.0-x86_64
        ipappend 2

Is there something wrong?

**Comment by Firxiao** [comment] 2015-05-27 08:56
check the network if there has other dhcp server

**Comment by robert-xiong** [comment] 2015-05-27 09:00
not possible.Because i use the VirtualBox to test cobbler.And the network mode is Host-Only Adapter.

**Comment by Firxiao** [comment] 2015-05-27 09:07
seem you use  centos7.0  , have you try centos7.1 ?

**Comment by robert-xiong** [comment] 2015-05-27 09:30
I am sorry.Is the iso need be this "CentOS-7-x86_64-NetInstall-1503.iso" ,or CentOS-7-x86_64-DVD-1503.iso is also okay?

**Comment by Firxiao** [comment] 2015-05-27 09:33
I think  it depends what packges what you want install,   I use  the CentOS-7-x86_64-DVD-1503-01.iso.

**Comment by robert-xiong** [comment] 2015-05-27 09:40
okay, got it.I haven't try the CentOS7.1. I am downloading the iso now.

**Comment by robert-xiong** [comment] 2015-05-27 09:50
Could you tell me your cobbler server OS version?

**Comment by Firxiao** [comment] 2015-05-27 09:52
OS : CentOS release 6.6 (Final)
cobbler: 2.6.3-1.el6

**Comment by Firxiao** [comment] 2015-05-27 10:03
I thought your problem is not the cobbler's problem but the the kickstart's problem , you can just use pxe with ks file install to test if this error appear again , you can try this guide 
https://access.redhat.com/documentation/zh-CN/Red_Hat_Enterprise_Linux/7/html/Installation_Guide/chap-booting-installer-x86.html#sect-booting-from-pxe-x86

**Comment by robert-xiong** [comment] 2015-05-27 10:08
That could be. Thank you ,i will try.

**Comment by Firxiao** [comment] 2015-05-28 01:04
Suddenly  remembered there has dhcp server  in Host-Only Adapter.   please check your   Host-Only Adapter and  make dhcp service disable. like this
![dhcp](https://cloud.githubusercontent.com/assets/2361088/7850702/4a98d0b6-0518-11e5-93d6-06db7330cad3.png)

**Comment by robert-xiong** [comment] 2015-05-28 01:14
yes, I have disable DHCP service of Host-Only Adapter.

**Comment by robert-xiong** [comment] 2015-05-28 07:52
I just build a PXE server ,no cobbler ,no kickstart.And it also stop here.It I am sure the vmlinuz and initrd.img are transported.So it could be what problem?

**Comment by Firxiao** [comment] 2015-05-28 10:15
pxe need a kickstart file ,  you can  use " system-config-kickstart  " to create .
this is my cobbler's ks file: 
http://firxiao.com/kickstarts/c7_mini.ks

**Comment by Firxiao** [comment] 2015-05-28 13:10
and have you try other vm software ? like vmware kvm .  or Physical machine？

**Comment by alanoe** [comment] 2015-05-28 13:14
Firxiao: a kickstart file is *not* required to boot a system via network using Cobbler (aka "pxe")

robert-xiong: the issue tracker is not a forum, use the Cobbler mailing list (cobbler@lists.fedorahosted.org) to post questions to Cobbler users and developers

**Comment by Firxiao** [comment] 2015-05-28 13:32
I just try leave kickstart file  blank, and  opps. 
![qq20150528-2 2x](https://cloud.githubusercontent.com/assets/2361088/7861057/6d1c418c-0580-11e5-8aa6-e9e9a3b7cbc2.png)

**Comment by Firxiao** [comment] 2015-05-28 14:14
alanoe:  so sorry , I just try leave kickstart file blank and add kernel options , It worked. but no kernel option and no kickstart file, it not worked.
robert-xiong:
do you make your pxe server step by step ? 
check " /var/lib/tftpboot/pxelinux/default "  is correct.
https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Installation_Guide/chap-installation-server-setup.html#sect-network-boot-setup-bios

**Comment by Firxiao** [comment] 2015-05-28 14:51
robert-xiong:  in your last image , I have seen  " rtnetlink answer file exits "  ,  might there has duplicate route.  could you issue " less /run/initramfs/rdsosreport.txt " ,    check what happen in last step
and also you can send log to the mailing list.

**Comment by requiemsallure** [comment] 2015-06-08 09:07
I don't know the reason in particular, but if you have multiple NICs on the server you are trying to kick-start you might need to put ksdevice=link in the kernel options, its what I had to do.

**Comment by robert-xiong** [comment] 2015-06-08 09:20
The problem is fixed.It should be the VirtualBox doesn't support the CentOS 7.0 boot from network.When I used the Physical machine,the problem is gone.Thank all you guys.
@christiangda could close the issue

**Comment by kemadz** [comment] 2015-12-22 12:09
In my case, change `ksdevice=eht0` to `ksdevice=link` fix the issue.

**Comment by dilshath** [comment] 2016-04-25 12:03
I am using centos 7 in physical machine. Unfortunately I partition the /dev/sda2 disk which contains /root/swap/home system directories so it showing this errors,

Dracut Error:



[ OK ] Reached target Paths.
[ OK ] Reached target Basic System.
dracut-initqueue[372]: Warning: Could not boot.
[ OK ] Started Show Plymouth Boot Screen.
[ OK ] Reached target Paths.
[ OK ] Reached target Basic System.
dracut-initqueue[372]: Warning: Could not boot.
dracut-initqueue[372]: Warning: /dev/centos/root does not exist.
dracut-initqueue[372]: Warning: /dev/centos/swap does not exist.
dracut-initqueue[372]: Warning: /dev/mapper/centos-root does not exist.
Starting Dracut Emergency Shell...
Warning: /dev/centos/root does not exist
Warning: /dev/centos/swap does not exist
Warning: /dev/mapper/centos-root does not exist

Generating "/run/initramfs/rdsosreport.txt"

Entering emergency mode. Exit the shell to continue.
Type "journalctl" to view system logs.
You might want to save "/run/initramfs/rdsosreport.txt" to a USB stick or /boot
after mounting them and attach it to a bug report.

dracut#


Anybody know how to fix the problem,please help me.

**Comment by jhlboy** [comment] 2016-05-18 03:01
![11](https://cloud.githubusercontent.com/assets/17328714/15345980/2463772a-1ce6-11e6-872c-356e69011e5d.jpg)
Cobbler installation of centos7.1-1503 set the static IP address of the installation error, the installation system in DHCP can be installed directly, without any error!

**Comment by weijianwen** [comment] 2017-05-12 15:50
It seems correlated to the default kickstart file (`/var/lib/cobbler/kickstarts/default.ks`) which is empty and is assigned to a profile when no option is passed to `--kickstart`. Recreating a profile with a usable kickstart file, for example `/var/lib/cobbler/kickstarts/sample_end.ks`, solves my problem. Please be cautious that `/var/lib/cobbler/kickstarts/sample.ks` does NOT work either. Even not tested yet, customized kickstart files based on `sample_end.ks` should work, I think.

```
# cobbler profile add --name=ks-sample-centos7-everything-1611-x86_64 --distro=centos7-everything-1611-x86_64 --kickstart=/var/lib/cobbler/kickstarts/sample_end.ks
# cobbler profile report --name=ks-sample-centos7-everything-1611-x86_64 | grep -i kickstart
Kickstart                      : /var/lib/cobbler/kickstarts/sample_end.ks
Kickstart Metadata             : {}
```

**Comment by BrandynX** [comment] 2017-06-21 07:06
Thank you for all the people here, your discussion helped me solve the problem that has plagued me for a long time.
I am using VMWare11 version, Cobble deployed Centos7.3, ESXI server no problem. But at home the computer will not work until I saw the robert-xiong final solution, began to suspect that the virtual machine is the problem, I usually choose the virtual machine is Centos 64 bit, until I changed to RHEL 7, everything is normal, It seems that this is related to the kernel version.
The Oh! My god, intermittently tried 10 times, lasted 2 months, thank you all, very grateful!

Above from google translation, thanks from Chinese IT engineers.

**Comment by hellth** [comment] 2017-08-31 09:25
This can be cause by lack of RAM on your VM, 1024 is not enough. Had the same error and increasing RAM helped me. My ksdevice is bootip and ks file is original, I haven't modified it, boot imge done from CentOS 7 64bit netinstall.

**Comment by RationalMonster** [comment] 2017-09-07 11:28
Yes,the 'hellth' :+1: ,it is rigtht! I suffer the same problem for a half year !
1.host machine OS：Ubuntu 16.04
2.build one guest  machines (CentOS-7.3.1611-Desktop)in Virtual Box as httpd. tftp. dhcp server to deploy CentOS-7.3.1611-Server  virtual machines by pxe+kickstart   
3.all the virtual machine network work in host only mode.

I got the same error like rebert-xiong everytime I tried until read this answer searched by Google.
I get one rediculous conclusion that DON'T USE Baidu TO SEARCH YOUR QUESTIONS IN CHINA.
who use who know.

**Comment by jmaas** [comment] 2017-09-10 09:17
So, not a bug.

**Closed by jmaas** 2017-09-10 09:17 UTC
Labels: bug_report

**Comment by ThanhTamPotter** [comment] 2017-10-04 13:41
@hellth thanks u so much!!! I cannot believe !! I had tried many times before  read your cmt.. thanks u so so so muchh...

**Comment by laoyin** [comment] 2018-06-25 18:02
i got this error, when i used maas to deploy centos7.  but target machine is just  Physical machine, DELL server.   i feel so sad, and i have no idea how to solve this problem .

**Comment by pingod** [comment] 2018-10-06 13:14
> pxe need a kickstart file , you can use " system-config-kickstart " to create .
> this is my cobbler's ks file:
> http://firxiao.com/kickstarts/c7_mini.ks

THK, it works

**Comment by cdyangzhenyu** [comment] 2019-03-06 01:27
> i got this error, when i used maas to deploy centos7. but target machine is just Physical machine, DELL server. i feel so sad, and i have no idea how to solve this problem .

I have same problem, did you sovle it?
