### ISSUE TITLE
Cobbler 3 release

### ISSUE THREAD

**Issue by brejoc** [cobbler/cobbler#2087] opened 2019-06-17 14:14 UTC
I'd like to start tracking the things that prevent us from releasing version 3.0.0.

- Non-technical: new project leadership / maintainers so that jmaas can step down.
- A working Cobbler Web
- Tested Cobbler & Cobbler Web on recent EL/Fedora/SuSE/Debian distros
- Documentation inside the src tree (Sphinx was choosen way back but can be changed) for better maintenance and to enable (force!) contributors s to also update the docs.
- Koan - do we still need it? Personally I feel it's not worth the effort

**Comment by brejoc** [comment] 2019-06-17 19:12
@jmaas, @watologo1, @SchoolGuy and others. We need a collection of stuff that is needed to ship the 3.0.0 release. So input is very welcome!

**Comment by SchoolGuy** [comment] 2019-06-18 06:22
I would suggest we add points in the first comment of @brejoc which we agree on.

My personal opinion is that we should merge the following PR's before we tag:
- <https://github.com/cobbler/cobbler/pull/2061>: Introduces Config-Changes, so we should probably merge this before 3.0. Admins are usually more cautious when migrating to a new major release instead of a minor one. (At least that is it what I detected about my own behavior!)
- <https://github.com/cobbler/cobbler/pull/2080>: I believe this is a rather important PR because it fixes a few things which are related to the web-interface which were omitted until now.
- <https://github.com/cobbler/cobbler/pull/2088>: This is related to the previous PR, so same reason.

As for the rest of the changes I would suggest that we try to fix/write docs for 3.0.0 and redirect old websites of cobbler to the current one and also store there also the docs for the old versions. Additionally I would start looking through the issues and close inactive ones as well as adding one which need to be fixed for the 3.0.0 release. The remaining ones I would put on a project board and work on them after the 3.0.0 release.

So much for the points we need to do before having a 3.0.0 tag.

P.S.: I would offer writing docs, providing examples and all that stuff for the website if no one else will do it.

**Comment by SchoolGuy** [comment] 2019-06-18 06:24
Oh and merge the Github-Wiki and the Docs. I wouldn't use the Github-Wiki if we have a website with Docs...

**Comment by watologo1** [comment] 2019-06-18 10:56
@SchoolGuy : No, this one must not merged before 3.0 tagging, but should go into the next (master and then 3.2? release):
#2061: Introduces Config-Changes, so we should probably merge this before 3.0. Admins are usually more cautious when migrating to a new major release instead of a minor one. (At least that is it what I detected about my own behavior!)

This is a cleanup which moves around all kind of files. Please do not destroy the whole git history, etc. where we are so stable and well tested already.

**Comment by kwizart** [comment] 2019-06-18 11:29
I haven't checked this but is the django web interface was updated to current python3/django ?

If no work is planned in this area, I may have an attempt to. But I would just like this change not to be hold for a "next release" (but don't block on this been broken either for 3.0.0 release either).

**Comment by brejoc** [comment] 2019-06-18 13:23
> I haven't checked this but is the django web interface was updated to current python3/django ?

Hm… good point. I don't know actually. At least we (SUSE) didn't touch that.

**Comment by watologo1** [comment] 2019-06-18 14:00
I still have to understand better the json distro matching files and the {autoinstall,kickstart} mess there.
From what I can see there is: /var/lib/cobbler/templates in the installed rpm, but I guess it should be
named /var/lib/cobbler/autoinstall_templates.
And in config/cobbler/distro_signatures.json there still are absolut paths:
    "default_kickstart":"/var/lib/cobbler/kickstarts/sample_autoyast.xml",
but I guess this should be default_autoinstall and relative to the autoinstall dir.
But I need more time to look into this to properly fix this.

**Comment by SchoolGuy** [comment] 2019-06-18 14:11
> @SchoolGuy : No, this one must not merged before 3.0 tagging, but should go into the next (master and then 3.2? release):
> #2061: Introduces Config-Changes, so we should probably merge this before 3.0. Admins are usually more cautious when migrating to a new major release instead of a minor one. (At least that is it what I detected about my own behavior!)
> 
> This is a cleanup which moves around all kind of files. Please do not destroy the whole git history, etc. where we are so stable and well tested already.

@watologo1 What git history is destroyed? I mean we are not deleting anything from the history... Testing we are doing because we have CI and since the CI says everything is fine I would trust that. If you think we need more tests I create them we need to do that anyway at some point in time.

**Comment by jmaas** [comment] 2019-06-19 09:09
I know I have been gone for a while, but I added some items in the opening post. Just opinions ;-)

**Comment by brejoc** [comment] 2019-06-19 11:43
Thanks a lot for your input @jmaas! It's really sad to see you go. I think everybody else is currently lacking overview! :cry: But of course I can understand that perfectly well. There are only 24 hours in a day and only so much you can do during the day. Thanks for sticking to this project for such a long time, for keeping it alive and also for making the transition to Python3 possible here in the upstream repo!

**Comment by brejoc** [comment] 2019-06-19 11:53
@watologo1 @SchoolGuy Regarding "Refactor modularization #2061". Like already mentioned there are only two options here. We either merge this for 3.0.0 or for the next major release. Merging this for a minor release would only cause trouble. That being said I don't agree with the perception that this is an exponential big change. It's mostly about moving files to sub-folders in order to get rid of file prefixes. Overview and maintainability would benefit form that. But of course this change would need to be tested. But with a major release we have to do it anyway. As far as I can see, the test-suite looks good so far. That's why I don't see a huge issue with the inclusion for 3.0.0.

@watologo1 I don't understand your comment about breaking the git history. What do you mean with that?

**Comment by SchoolGuy** [comment] 2019-06-19 11:57
I have to maintain and rebase that PR every time someone does some bigger changes, so I would really appreciate if we could merge this as quick as reasonable. I am happy to extend the tests for specific cases if someone thinks we need a special one for these changes.

**Comment by jmaas** [comment] 2019-06-19 12:45
i'd say merge it, 3.0 is a big change anyway. is not compatible with 2.8 as some data structures changed (eg. system), compatibility code has been removed etc. etc.

**Comment by watologo1** [comment] 2019-06-19 13:47
About: "Refactor modularization #2061"
Please add this after 3.0 tagging/releasing.
SuMa 4.0 is more or less cobbler 3.0 based. Doing diffs and searching for important bug fixes in the future is easy if the code base is more or less the same.
If you move around files now with some thousand lines changed, you do not find any change between 3.0 release mainline cobbler (and bugfixes will be added to this release) and the SuMa released cobbler.
With git history breakage I mean "git annotate/blame". Currently if you do a git annotate on code you suspect to be the reason of breakage, you still might get a good hint pointing to the last code change.
Once files are moved around you are always pointed to "moved file for refactor modularization" commit. This is ok with 3.2, but please do not do this with the upcoming and hopefully SuMa based 3.0 release. There really should only important bugfixes pushed now.
I also do not mind about just tagging/releasing and push bugfixes into 3.0 additionally.

**Comment by thiller2018** [comment] 2019-06-26 11:55
> > I haven't checked this but is the django web interface was updated to current python3/django ?
> 
> Hm… good point. I don't know actually. At least we (SUSE) didn't touch that.

I made some changes, so that the GUI actually is coming up. Clicking on some buttons will show errors, so there are more changes needed like sorting of dicts.

**Comment by watologo1** [comment] 2019-06-28 14:42
.. like sorting of dicts.

I had a look at the converting of the lambda function into a loop (and the reference you sent me privately).
From what I could see, the use of the lambda function in the function header is intended and is the common way to compare dict elements when sorting.
Please explain in detail what exactly is failing, best how to reproduce, maybe in a tiny example.

**Comment by thiller2018** [comment] 2019-06-28 14:54
> 
> 
> .. like sorting of dicts.
> 
> I had a look at the converting of the lambda function into a loop (and the reference you sent me privately).
> From what I could see, the use of the lambda function in the function header is intended and is the common way to compare dict elements when sorting.
> Please explain in detail what exactly is failing, best how to reproduce, maybe in a tiny example.

The sort uses a compare method, which is no longer supported with Python 3. You have to use a key instead. The change basically makes a key out of a cmp function, so that it works in Python 3.

From https://docs.python.org/3/howto/sorting.html?highlight=sorting 
... all of the Py2.x versions supported a cmp parameter to handle user specified comparison functions.
In Py3.0, the cmp parameter was removed entirely
When porting code from Python 2.x to 3.x, the situation can arise when you have the user supplying a comparison function and you need to convert that to a key function. The following wrapper makes that easy to do:
... key=cmp_to_key(reverse_numeric) ...

**Comment by arozenfe** [comment] 2019-07-04 18:29
@brejoc, FWIW I think koan is an indispensable part of Cobbler. Without the ability to easily reinstall machines and install VMs that koan provides, Cobbler would lose much of it's core functionality.

**Comment by SchoolGuy** [comment] 2019-07-05 13:06
@arozenfe That was actually jmasses edit. But yes I also see that we still need koan.

**Comment by SchoolGuy** [comment] 2019-07-16 14:31
@brejoc @watologo1 @thiller2018 @arozenfe @kwizart Do we agree on Sphinx as a doc-tool? 

Additionally I would love to merge the github pages website and cobblerd.org to create a single website where users can get their information and everything which we want to publish about this.

**Comment by watologo1** [comment] 2019-07-16 15:41
@SchoolGuy There is an open issue about dead links in documentation somewhere, right?
Hmm, still... I'd really like to see a release tagged (best without much more features/cleanups).
Afaik Jochen wants to wait for fedora packaging fixes which someone may come up soon. This would indeed be nice to have before people try hard on a released version. But if this is not showing up soon, we should simply hit the button.
I hate projects with no releases. There are projects tagging every month...
Why not publish 3.0.1 as soon as the cleanups you mentioned (also Fedora packaging fixes) finally show up...?

**Comment by SchoolGuy** [comment] 2019-07-17 05:05
@watologo1 As far as I can oversee this I have nothing against tagging soon and releasing 3.0.1 when the Fedora Fixes are inside master. But we currently have not enough documentation to use cobbler 3.0 and the old documentation is spread to much to count it as reliable. Users would be confused. Personally I got already an internal ticket from docs asking about cobbler because they couldn't find anything satisfactory in the upstream docs.

**Comment by kwizart** [comment] 2019-07-17 06:01
I'm not sure about what you mean about releasing 3.0.0 are we going to have alpha/beta/rc phases ?
Is there any ticket for the Fedora/RHEL packaging issue (I haven't tried master for a while).

**Comment by SchoolGuy** [comment] 2019-08-15 09:37
The release has happend, so I will close this one now. For a future new release we can pick up the stuff from here if we want to.

**Closed by SchoolGuy** 2019-08-15 09:37 UTC
