### ISSUE TITLE
anamon is invalid

### ISSUE THREAD

**Issue by maojianer** [cobbler/cobbler#2762] opened 2021-08-25 13:39 UTC
### Describe the bug

When the client is installed centos7.9, the server anamon cannot see the log
Client error

![2ddddbec6e238a100cf5dfe2241b123](https://user-images.githubusercontent.com/31433715/130799678-46152f28-9436-43b8-882b-68a961d07a57.png)

### Expected behavior

```bash
ll /var/log/cobbler/anamon/
```
 This directory should have logs, it is blank now

![image](https://user-images.githubusercontent.com/31433715/130800822-91f8bc95-1b3f-4602-bdec-af5f6ef49008.png)

### Cobbler version

````bash
Cobbler 3.2.1
  source: ?, ?
  build time: Sun Aug 22 12:29:58 2021
````

### Operating system
CentOS Linux release 8.4.2105

### Cobbler log

![image](https://user-images.githubusercontent.com/31433715/130800396-6443ae5c-cc57-43b7-b1d2-c4f6bca3efbb.png)

**Comment by AaronBandt** [comment] 2022-08-23 13:09
Is there any update on a path forward for this? It is still failing on cobbler 3.3.3 because the server wants bytes now.

**Comment by SchoolGuy** [comment] 2022-08-24 07:24
I have no knowledge of that process sadly and my priorities at work do not allow me to work on this atm. My free time is at the moment occupied differently, thus I have no plans at the moment. Feel free to open a PR to fix the issue or to describe the issue in such details that the fix is very straightforward to do. I will gladly assist when opening a PR.

**Comment by AaronBandt** [comment] 2022-08-24 17:45
Sounds good, I will see what I can do to fix it and will follow up here when I have something, thanks!

**Comment by ckotte** [comment] 2022-12-02 11:04
@AaronBandt Do you have any errors in the cobbler.log on 3.3.3? I'm using main. Anamon doesn't work, but I don't errors like this in the log..

**Comment by ckotte** [comment] 2022-12-06 18:08
@AaronBandt I switched back to 3.2.2 and I still have anamon errors. Does it work for you with 3.2.2??

/tmp/anamon --name "FQDN" --server "SERVER" --port "80" --debug
```
upload_log_data('FQDN', 'anaconda.log', 12, 0, ...)
```

cobbler.log
```
2022-12-06T18:33:36 - WARNING | upload_log_data - One of the parameters handed over had an invalid type!
```

**Comment by ckotte** [comment] 2022-12-06 18:14
> I can confirm that i have reproduced this with CentOS 8 also. The tricky part is that we need to be able to write bytes, as well as strings into a file now.

Why do you change the API to require bytes, but don't change the anamon script? Are there other parts in cobbler which use `upload_log_data`  function and can successfully write files?

**Comment by AaronBandt** [comment] 2022-12-07 18:25
> @AaronBandt I switched back to 3.2.2 and I still have anamon errors. Does it work for you with 3.2.2??
> 
> /tmp/anamon --name "FQDN" --server "SERVER" --port "80" --debug
> 
> ```
> upload_log_data('FQDN', 'anaconda.log', 12, 0, ...)
> ```
> 
> cobbler.log
> 
> ```
> 2022-12-06T18:33:36 - WARNING | upload_log_data - One of the parameters handed over had an invalid type!
> ```

@ckotte No, sorry I wasn't more clear. It does not work on 3.2.2 either. Last place I know it worked for sure was 2.8.5

**Comment by SchoolGuy** [comment] 2022-12-08 10:36
@AaronBandt @ckotte  That could be fixed with a patch. Due to a recent CVE we had to tighten the things that can be uploaded. Thus If you tell me what types to expect where I can create a hotfix patch for you that I can post here. However due to my lack of knowledge with said process I am unable to create this by myself.

**Comment by ckotte** [comment] 2022-12-08 15:00
@SchoolGuy I tested it locally on the cobbler server itself. The strange thing is that the type is bytes when it is handed over to the function in the anamon script. At the server it's not bytes anymore.

**Comment by SchoolGuy** [comment] 2022-12-08 16:27
Yes that is exactly my point. Python 2 & 3 changed the str data types. The XML-RPC library is the one converting the data from XML to Python data. Thus I believe we need to able to handle both incoming Python 2 script data and Python 3 script data.

**Comment by SchoolGuy** [comment] 2023-04-29 09:53
I see this issue as a duplicate of #3324. Thus closing the issue.

**Closed by SchoolGuy** 2023-04-29 09:53 UTC
Labels: Bug Report, 3.2.1, 3.3.3
