### ISSUE TITLE
[CI] Building Tumbleweed RPMs fails

### ISSUE THREAD

**Issue by nodeg** [cobbler/cobbler#2811] opened 2021-09-29 08:39 UTC
### Describe the bug

We need to look into the following issue when building the Tumbleweed RPMs in the CI:
```bash
Step 4/11 : RUN zypper dup -y
 ---> Running in 61a6eaabd809
terminate called after throwing an instance of 'std::system_error'
  what():  Operation not permitted
The command '/bin/sh -c zypper dup -y' returned a non-zero code: 139
```
I saw this error in 3 pull request.

**Comment by SchoolGuy** [comment] 2021-09-29 09:17
So I can't reproduce this locally. Thus I need to spam #2810 until I find a solution for the problem...

**Comment by SchoolGuy** [comment] 2021-09-29 09:21
Okay we can't do anything until https://bugzilla.suse.com/show_bug.cgi?id=1190670 is solved. Kudos to @vogtinator for finding it for me.

**Comment by nodeg** [comment] 2021-09-29 09:24
Ok. So another glibc 2.34 issue.

**Comment by SchoolGuy** [comment] 2021-09-29 09:27
Example of the failure: https://github.com/cobbler/cobbler/pull/2810/checks?check_run_id=3742282637#step:3:164

**Comment by SchoolGuy** [comment] 2021-12-15 15:19
This is fixed in the meantime. Thus we can close it.

**Closed by SchoolGuy** 2021-12-15 15:19 UTC
Labels: Bug Report, CI
