### ISSUE TITLE
Expect container releases

### ISSUE THREAD

**Issue by Jack-Ywn** [cobbler/cobbler#2567] opened 2021-03-02 12:51 UTC
Expect to release a container version of the deployment

**Comment by SchoolGuy** [comment] 2021-03-02 13:39
Currently it is not easy to run Cobbler inside a Docker Container. Since we are near the release of `3.2.1` (only a few left), we will append that to `3.3.0`. Official support for a production environment in a container for Cobbler will hit with `4.0.0`-

**Comment by dansou901** [comment] 2021-03-04 11:45
This will also need a few customizations to the startup behaviour of cobblerd. I propose that all folders in which custom stuff like images, repos, profiles and so on are stored will be created on startup if they don't exist. As soon as that's implemented, it'll be quite easy to build a docker image for production usage.

**Comment by dansou901** [comment] 2021-03-04 11:45
For now, these directories are created at install time. This is not sufficient for docker images.

**Comment by SchoolGuy** [comment] 2021-03-04 13:03
@dansou901 That is indeed a helpful hint and would take those steps away from the installation and we would be more resiliant against problems. So we need to add that to this task.

**Comment by SchoolGuy** [comment] 2021-12-15 15:25
This is a duplicate of #2453 and can thus be closed.

**Closed by SchoolGuy** 2021-12-15 15:25 UTC
Labels: Feature Request
