### ISSUE TITLE
cobbler signature for ubuntu 20/focal 

### ISSUE THREAD

**Issue by darkrat3d** [cobbler/cobbler#2364] opened 2020-06-25 20:55 UTC
Im trying to import new iso.   and im getting signature error.   this one both errors on desktop and live-sever. 

```
# cobbler signature update
task started: 2020-06-25_135125_sigupdate
task started (id=Updating Signatures, time=Thu Jun 25 13:51:25 2020)
running python triggers from /var/lib/cobbler/triggers/task/sigupdate/pre/*
running shell triggers from /var/lib/cobbler/triggers/task/sigupdate/pre/*
shell triggers finished successfully
Successfully got file from https://cobbler.github.io/signatures/3.0.x/latest.json
*** TASK COMPLETE ***
```
```
# cobbler signature report --name=ubuntu
Currently loaded signatures:
ubuntu:
        artful
        bionic
        cosmic
        disco
        eoan
        lucid
        oneiric
        precise
        quantal
        raring
        saucy
        trusty
        utopic
        vivid
        wily
        xenial
        yakkety
        zesty
```

**Comment by nvtkaszpir** [comment] 2020-06-28 08:20
Please see https://github.com/cobbler/cobbler/issues/2339#issuecomment-647820367

**Comment by SchoolGuy** [comment] 2020-06-28 14:57
Since this is already existing I will close this as a duplicate of #2339

**Closed by SchoolGuy** 2020-06-28 14:57 UTC
Labels: Feature Request
