### ISSUE TITLE
Built-in TFTP server tftpd.py on release28 doesn't work out of the box; Fix included

### ISSUE THREAD

**Issue by charles-m-knox** [cobbler/cobbler#2016] opened 2019-02-05 21:36 UTC
When using Cobbler on the branch `release28`, opting to use the built-in [`tftpd.py`](https://github.com/cobbler/cobbler/blob/release28/bin/tftpd.py) TFTP server doesn't work properly.

Namely, references to the constructor for the `ERRORPacket` class are used incorrectly; they seem to pass the wrong number of arguments to the constructor, and as a result, exceptions are thrown and downstream TFTP clients never receive proper UDP error packets. Because of this, any time a TFTP client tries to `GET` a file that doesn't exist, it times out instead of immediately receiving a packet containing "file not found" (error code 1).

In my environment, this causes clients that are attempting to PXE boot to take >30 minutes due to them trying a few files before settling on `pxelinux.cfg/default`.

Since the file has not been touched for years (oct 2015), I'm wondering if anyone else has run into this issue. Fortunately, I was able to conjure up a fix and have verified it working in a few setups. I'll describe the fix next, and read down below for my steps on using the (modified) built-in `tftpd.py` server.

---

The fix itself is what I want to point out first; I added a `@staticmethod` to that `ERRORPacket` class [here](https://gist.github.com/charles-m-knox/5e45911102a8d3b50165c39d37fbc8f2#file-tftpd-py-L258-L261), and then updated all spots where `ERRORPacket` classes were instantiated - there were a few spots, so search the page for `ERRORPacket.static_marshall` and you'll find them.

The error in the Python code was that [`ERRORPacket` requires 4 args for its constructor](https://github.com/cobbler/cobbler/blob/release28/bin/tftpd.py#L240), but basically everywhere else in the code it's being used with fewer arguments, [for example](https://github.com/cobbler/cobbler/blob/release28/bin/tftpd.py#L868-L877):

```python
# Line 868, /bin/tftpd.py
local_sock.sendto(ERRORPacket(0,"Unknown request").marshall(), remote_addr)
```

After my fix, the usage is now:

```python
# Line 885, /bin/tftpd.py, on my linked gist
local_sock.sendto(ERRORPacket.static_marshall(0,"Unknown request"), remote_addr)
```

See here: https://gist.github.com/charles-m-knox/5e45911102a8d3b50165c39d37fbc8f2#file-tftpd-py-L885
And another example here, which passes 4 proper arguments to the `ERRORPacket` constructor: https://gist.github.com/charles-m-knox/5e45911102a8d3b50165c39d37fbc8f2#file-tftpd-py-L774-L778

My fix may not be the cleanest approach; one could simply add the `@staticmethod` decorator to the `marshall` function and update the rest of the references to it similarly, but I was pressed for time while investigating this, and found it easier to simply add a new function and use that one (this way, I didn't have to worry about breaking any existing code that I hadn't inspected yet).

I hope this helps anyone else that runs into problems with `tftpd.py`. I am very thankful for the efforts that have been put in on Cobbler, the developers have done a great job. Read below for instructions on how to use the script.

---

_This setup assumes you're using `xinetd` to handle incoming TFTP connections_

 _Disclaimer: This may contain configuration values different from a "vanilla" setup._

First, edit `/etc/cobbler/modules.conf` and under the `[tftpd]` section, ensure this configuration option is set:

```
[tftpd]
module = manage_tftpd_py
```

Then, edit `/etc/cobbler/tftpd.template` (which is required by the module we set above, [seen here](https://github.com/cobbler/cobbler/blob/release28/cobbler/modules/manage_in_tftpd.py#L119)) to include the following:

```
service tftp
{
        disable                 = no
        socket_type             = dgram
        protocol                = udp
        wait                    = yes
        user                    = $user
        server                  = $binary
        server_args             = -d -v --prefix=/var/lib/tftpboot
        per_source              = 11
        cps                     = 100 2
        flags                   = IPv4
}
```

_You can probably mess with `$args` instead of what I've got there for `server_args` to get the same result, but my environment has a bunch more complexities that made it unrealistic to do it that way._

Then, download my custom version of `tftpd.py` to `/usr/sbin/tftpd.py` and make it executable:

_If you're skeptical about downloading this file, do a `diff` between [Cobbler's `tftpd.py`](https://github.com/cobbler/cobbler/blob/release28/bin/tftpd.py) and [mine](https://gist.github.com/charles-m-knox/5e45911102a8d3b50165c39d37fbc8f2)_

```bash
wget https://gist.githubusercontent.com/charles-m-knox/5e45911102a8d3b50165c39d37fbc8f2/raw/101ccdc800ea983a63ee70448a2d65a32df3f216/tftpd.py && \
mv tftpd.py /usr/sbin/tftpd.py && \
chmod +x /usr/sbin/tftpd.py
```

Turn off `atftpd` by running `systemctl stop atftpd`. Then run the following to configure xinetd & cobbler to use our new setup:

```bash
systemctl restart cobblerd.service
cobbler sync
systemctl restart xinetd.service
```

As part of the `cobbler sync` command it will update `/etc/xinetd.d/tftp`; validate that this file looks like this (ignoring the comments at the top of the file):

```
service tftp
{
        disable                 = no
        socket_type             = dgram
        protocol                = udp
        wait                    = yes
        user                    = nobody
        server                  = /usr/sbin/tftpd.py
        server_args             = -d -v --prefix=/var/lib/tftpboot
        per_source              = 11
        cps                     = 100 2
        flags                   = IPv4
}
```

With the `-d -v` flags you get debug and verbose log output, check `/var/log/syslog` while doing TFTP client transactions to see how things look. **_If you pull down the upstream `version28` code instead of mine, you'll likely see exceptions being thrown, and your client timing out._**

Thanks for reading this. To the developers reading this, I'll let you ponder/discuss what steps to take, you're welcome to use my code if needed.

**Comment by jmaas** [comment] 2019-02-07 12:57
Hi thanks for your report. I dont think there's many users actually using the python based tftpd.
You did a great job of writing down the issue as well as providing a fix.
Could you please send a pull request for the 2.8 branch? Then we can ship this fix in the next release.

For Cobbler 3 i think the python tftpd will be removed....

**Comment by charles-m-knox** [comment] 2019-02-08 22:29
I created it as PR #2018. Thanks for your response @jmaas

**Comment by kwizart** [comment] 2019-06-03 12:44
seems like the issue is fixed, can you consider closing the bug ?

**Comment by watologo1** [comment] 2019-06-04 15:07
JFYI: I like to drop the tftpd.py code for 3.0.
There are quite some ugly hacks (even named like that in comments), which prevent cleanups in main cobbler code as well.
Please let me know if not.
I thought this one is rather unused. xinetd is outdated for quite a while and I reverted this configs recently as well.

**Closed by watologo1** 2019-06-04 15:07 UTC
