### ISSUE TITLE
UEFI support

### ISSUE THREAD

**Issue by celesteking** [cobbler/cobbler#1777] opened 2017-03-28 15:20 UTC
koan / cobbler needs to support UEFI and ability to choose it by some means. 

for ex., virt-install supports --boot uefi , assuming virsh domcapabilities lists it (it does here). So the missing piece is either koan's support for it or autoguessing based on cobbler-supplied parameter.

**Comment by celesteking** [comment] 2017-06-16 12:05
This is incorporated in https://github.com/celesteking/cobbler/pull/1 , if anyone needs that.

**Comment by jmaas** [comment] 2017-06-25 13:56
please send pull requests for master and release28 :)

**Comment by SchoolGuy** [comment] 2020-09-25 09:23
So to support UEFI we need to be able to do the following things:

- [ ] Generate configs for the PXE/HTTP-Boot/...
- [ ] `cobbler buildiso` needs to support this
- [ ] Koan needs to be able to detect and set this up in `virsh` --> Separate issue in Koan.
- [ ] We need to distingish between a system which is booted via (U)EFI and and via legacy.
- [ ] We need to document how this is working so everyone can use it.
- [ ] We need tests to check if this is working.

**Comment by SchoolGuy** [comment] 2020-09-25 09:25
I found already linked the following PR: https://github.com/celesteking/cobbler/pull/1

Below is the patch generated from the PR.

```patch
From 91c46883a02e5ce72b04d1116f81e4c91449b8cd Mon Sep 17 00:00:00 2001
From: Yuri A <yuri@theta.local>
Date: Fri, 16 Jun 2017 07:24:06 -0400
Subject: [PATCH 1/4] koan: Add support for virt_disk_sectors and
 virt_uefi_boot params.

---
 koan/app.py         | 32 +++++++++++++++++++++++++++++---
 koan/virtinstall.py | 22 +++++++++++++++++-----
 2 files changed, 46 insertions(+), 8 deletions(-)

diff --git a/koan/app.py b/koan/app.py
index a6ed9ec83..f122438f6 100755
--- a/koan/app.py
+++ b/koan/app.py
@@ -81,9 +81,11 @@
    "virt_ram",
    "virt_disk",
    "virt_disk_driver",
+   "virt_disk_sectors",
    "virt_type",
    "virt_path",
    "virt_auto_boot",
+   "virt_uefi_boot",
    "virt_pxe_boot",
 ]
 
@@ -327,6 +329,7 @@ def __init__(self):
         self.qemu_machine_type = None
         self.virt_auto_boot    = None
         self.virt_pxe_boot     = None
+        self.virt_uefi_boot    = None
         self.virtinstall_wait  = None
         self.virtinstall_noreboot = None
         self.virtinstall_osimport = None
@@ -1510,12 +1513,14 @@ def virt_net_install(self,profile_data):
         path_list           = self.calc_virt_path(pd, virtname)
         size_list           = self.calc_virt_filesize(pd)
         driver_list         = self.calc_virt_drivers(pd)
+        sectors_list        = self.calc_virt_disk_sectors(pd)
         if self.virt_type == 'openvz':
             disks = None
         else:
-            disks           = self.merge_disk_data(path_list,size_list,driver_list)
+            disks           = self.merge_disk_data(path_list,size_list,driver_list, sectors_list)
         virt_auto_boot      = self.calc_virt_autoboot(pd, self.virt_auto_boot)
         virt_pxe_boot       = self.calc_virt_pxeboot(pd, self.virt_pxe_boot)
+        virt_uefi_boot      = self.calc_virt_uefiboot(pd, self.virt_uefi_boot)
 
         results = create_func(
                 name              =  virtname,
@@ -1532,6 +1537,7 @@ def virt_net_install(self,profile_data):
                 virt_type         =  self.virt_type,
                 virt_auto_boot    =  virt_auto_boot,
                 virt_pxe_boot     =  virt_pxe_boot,
+                virt_uefi_boot    =  virt_uefi_boot,
                 qemu_driver_type  =  self.qemu_disk_type,
                 qemu_net_type     =  self.qemu_net_type,
                 qemu_machine_type =  self.qemu_machine_type,
@@ -1635,7 +1641,7 @@ def virt_choose(self, pd):
 
     #---------------------------------------------------
 
-    def merge_disk_data(self, paths, sizes, drivers):
+    def merge_disk_data(self, paths, sizes, drivers, sectors):
         counter = 0
         disks = []
         for p in paths:
@@ -1648,7 +1654,8 @@ def merge_disk_data(self, paths, sizes, drivers):
                 driver = drivers[-1]
             else:
                 driver = drivers[counter]
-            disks.append([path,size,driver])
+            sector_size = sectors[counter]
+            disks.append([path,size,driver,sector_size])
             counter = counter + 1
         if len(disks) == 0:
             print "paths:   ", paths
@@ -1705,6 +1712,19 @@ def calc_virt_pxeboot(self,data,override_pxeboot=False):
 
     #--------------------------------------------------
 
+    def calc_virt_uefiboot(self,data,override=False):
+        if override:
+           return True
+
+        val = str(self.safe_load(data,'virt_uefi_boot',0)).lower()
+
+        if val in [ "1", "true", "y", "yes" ]:
+           return True
+
+        return False
+
+    #--------------------------------------------------
+
     def calc_virt_filesize(self,data,default_filesize=0):
 
         # MAJOR FIXME: are there overrides?  
@@ -1756,6 +1776,12 @@ def calc_virt_drivers(self,data):
 
     #---------------------------------------------------
 
+    def calc_virt_disk_sectors(self, data):
+        secs = self.safe_load(data,'virt_disk_sectors',default='raw')
+        return secs.split(",")
+
+    #---------------------------------------------------
+
     def calc_virt_ram(self,data,default_ram=64):
         """
         Assign a virt ram size if none is given in the profile.
diff --git a/koan/virtinstall.py b/koan/virtinstall.py
index 320f7dabf..6aebaa01d 100644
--- a/koan/virtinstall.py
+++ b/koan/virtinstall.py
@@ -32,6 +32,7 @@
 
 import app as koan
 import utils
+from distutils.version import StrictVersion
 
 # The virtinst module will no longer be availabe to import in some
 # distros. We need to get all the info we need from the virt-install
@@ -97,7 +98,7 @@ def _sanitize_disks(disks):
             driver_type = d[2]
 
         if d[1] != 0 or d[0].startswith("/dev"):
-            ret.append((d[0], d[1], driver_type))
+            ret.append((d[0], d[1], driver_type, d[3]))
         else:
             raise koan.InfoException("this virtualization type does not work without a disk image, set virt-size in Cobbler to non-zero")
 
@@ -154,7 +155,7 @@ def _sanitize_nics(nics, bridge, profile_bridge, network_count):
 
 def create_image_file(disks=None, **kwargs):
     disks = _sanitize_disks(disks)
-    for path, size, driver_type in disks:
+    for path, size, driver_type, ss in disks:
         if driver_type is None:
             continue
         if os.path.isdir(path) or os.path.exists(path):
@@ -178,6 +179,7 @@ def build_commandline(uri,
                       virt_type=None,
                       virt_auto_boot=False,
                       virt_pxe_boot=False,
+                      virt_uefi_boot=False,
                       qemu_driver_type=None,
                       qemu_net_type=None,
                       qemu_machine_type=None,
@@ -355,6 +357,9 @@ def build_commandline(uri,
             cmd += "--import "
             import_exists = True
 
+        if virt_uefi_boot:
+            cmd += "--boot uefi "
+
         if arch:
             cmd += "--arch %s " % arch
     else:
@@ -406,9 +411,9 @@ def build_commandline(uri,
         # This needs to be the first disk for import to work
         cmd += "--disk path=%s " % importpath
 
-    for path, size, driver_type in disks:
-        print ("- adding disk: %s of size %s (driver type=%s)" %
-               (path, size, driver_type))
+    for path, size, driver_type, sector_size in disks:
+        print ("- adding disk: %s of size %s (driver type=%s sector_size=%s)" %
+               (path, size, driver_type, sector_size))
         cmd += "--disk path=%s" % (path)
         if str(size) != "0":
             cmd += ",size=%s" % size
@@ -416,6 +421,13 @@ def build_commandline(uri,
             cmd += ",bus=%s" % disk_bus
         if driver_type and not disable_driver_type:
             cmd += ",format=%s" % driver_type
+	if sector_size and StrictVersion(virtinst_version) >= StrictVersion('1.4.0'):
+	    lbs, pbs = {		
+                '4kn':  (4096, 4096),
+                '512e': (512, 4096),
+                '512':  (512, 512),
+	    }[sector_size.lower()]
+	    cmd += ",physical_block_size=%s,logical_block_size=%s" % (pbs,lbs)
         cmd += " "
 
     if floppy:

From 159bf524dd5d561a6e2582ce94d9d41e50229c80 Mon Sep 17 00:00:00 2001
From: Yuri A <yuri@theta.local>
Date: Fri, 16 Jun 2017 07:42:12 -0400
Subject: [PATCH 2/4] cobbler: Add support for specifying disk sector size via
 virt_disk_sectors and whether to boot host over UEFI via virt_uefi_boot
 params.

---
 cobbler/field_info.py   |  3 +++
 cobbler/item_profile.py |  8 ++++++++
 cobbler/item_system.py  |  8 ++++++++
 cobbler/utils.py        | 35 +++++++++++++++++++++++++++++++++++
 4 files changed, 54 insertions(+)

diff --git a/cobbler/field_info.py b/cobbler/field_info.py
index 52b23c986..d447b6d98 100644
--- a/cobbler/field_info.py
+++ b/cobbler/field_info.py
@@ -74,6 +74,7 @@
    "ipv6_autoconfiguration",
    "keep_updated",
    "mirror_locally",
+   "virt_uefi_boot",
    "virt_auto_boot",
    "virt_pxe_boot",
    "*repos_enabled",
@@ -102,8 +103,10 @@
    "virt_path"       : "Virtualization",
    "virt_file_size"  : "Virtualization",
    "virt_disk_driver": "Virtualization",
+   "virt_disk_sectors": "Virtualization",
    "virt_type"       : "Virtualization",
    "virt_auto_boot"  : "Virtualization",
+   "virt_uefi_boot"  : "Virtualization",
    "virt_pxe_boot"   : "Virtualization",
    "virt_host"       : "Virtualization",
    "virt_group"      : "Virtualization",
diff --git a/cobbler/item_profile.py b/cobbler/item_profile.py
index 2cba61271..7b932b07a 100644
--- a/cobbler/item_profile.py
+++ b/cobbler/item_profile.py
@@ -44,8 +44,10 @@
   ["repos",[],'<<inherit>>',"Repos",True,"Repos to auto-assign to this profile",[],"list"],
   ["comment","","","Comment",True,"Free form text description",0,"str"],
   ["virt_auto_boot","SETTINGS:virt_auto_boot",'<<inherit>>',"Virt Auto Boot",True,"Auto boot this VM?",0,"bool"],
+  ["virt_uefi_boot",0,'<<inherit>>',"Virt UEFI Boot",True,"Boot VM in UEFI mode?",0,"bool"],
   ["virt_cpus",1,'<<inherit>>',"Virt CPUs",True,"integer",0,"int"],
   ["virt_file_size","SETTINGS:default_virt_file_size",'<<inherit>>',"Virt File Size(GB)",True,"",0,"int"],
+  ["virt_disk_sectors",'512','<<inherit>>',"Virt Disk Sector Size",True,"512e or 512 or 4Kn, comma separated for more", 0,"str"],
   ["virt_disk_driver","SETTINGS:default_virt_disk_driver",'<<inherit>>',"Virt Disk Driver Type",True,"The on-disk format for the virtualization disk","raw","str"],
   ["virt_ram","SETTINGS:default_virt_ram",'<<inherit>>',"Virt RAM (MB)",True,"",0,"int"],
   ["depth",1,1,"",False,"",0,"int"],
@@ -212,6 +214,9 @@ def set_kickstart(self,kickstart):
     def set_virt_auto_boot(self,num):
         return utils.set_virt_auto_boot(self,num)
 
+    def set_virt_uefi_boot(self,num):
+        return utils.set_virt_uefi_boot(self,num)
+
     def set_virt_cpus(self,num):
         return utils.set_virt_cpus(self,num)
 
@@ -221,6 +226,9 @@ def set_virt_file_size(self,num):
     def set_virt_disk_driver(self,driver):
         return utils.set_virt_disk_driver(self,driver)
 
+    def set_virt_disk_sectors(self,val):
+        return utils.set_virt_disk_sectors(self,val)
+
     def set_virt_ram(self,num):
         return utils.set_virt_ram(self,num)
 
diff --git a/cobbler/item_system.py b/cobbler/item_system.py
index cc5a6d1cd..212fa52d0 100644
--- a/cobbler/item_system.py
+++ b/cobbler/item_system.py
@@ -44,10 +44,12 @@
   ["comment","",0,"Comment",True,"Free form text description",0,"str"],
   ["depth",2,0,"",False,"",0,"int"],
   ["server","<<inherit>>",0,"Server Override",True,"See manpage or leave blank",0,"str"],
+  ["virt_uefi_boot","<<inherit>>",0,"Virt UEFI Boot",True,"Boot VM in UEFI mode?",0,"bool"],
   ["virt_path","<<inherit>>",0,"Virt Path",True,"Ex: /directory or VolGroup00",0,"str"],
   ["virt_type","<<inherit>>",0,"Virt Type",True,"Virtualization technology to use",["xenpv","xenfv","qemu","kvm","vmware","openvz"],"str"],
   ["virt_cpus","<<inherit>>",0,"Virt CPUs",True,"",0,"int"],
   ["virt_file_size","<<inherit>>",0,"Virt File Size(GB)",True,"",0,"float"],
+  ["virt_disk_sectors","<<inherit>>",0,"Virt Disk Sector Size",True,"512e or 512 or 4Kn, comma separated for more", 0,"str"],
   ["virt_disk_driver","<<inherit>>",0,"Virt Disk Driver Type",True,"The on-disk format for the virtualization disk",["<<inherit>>","raw"],"str"],
   ["virt_ram","<<inherit>>",0,"Virt RAM (MB)",True,"",0,"int"],
   ["virt_auto_boot","<<inherit>>",0,"Virt Auto Boot",True,"Auto boot this VM?",0,"bool"],
@@ -590,9 +592,15 @@ def set_virt_file_size(self,num):
     def set_virt_disk_driver(self,driver):
         return utils.set_virt_disk_driver(self,driver)
 
+    def set_virt_disk_sectors(self,val):
+        return utils.set_virt_disk_sectors(self,val)
+
     def set_virt_auto_boot(self,num):
         return utils.set_virt_auto_boot(self,num)
 
+    def set_virt_uefi_boot(self,num):
+        return utils.set_virt_uefi_boot(self,num)
+
     def set_virt_pxe_boot(self,num):
         return utils.set_virt_pxe_boot(self,num)
 
diff --git a/cobbler/utils.py b/cobbler/utils.py
index a550c6850..276d2101b 100644
--- a/cobbler/utils.py
+++ b/cobbler/utils.py
@@ -1437,6 +1437,21 @@ def set_virt_disk_driver(self,driver):
     self.virt_disk_driver = driver
     return True
 
+def set_virt_disk_sectors(self,vals):
+    """
+    For Virt only.
+    """
+    if vals != '<<inherit>>':
+        tokens = vals.split(",")
+        for t in tokens:
+            if not re.search('^(512|512e|4kn)$', t, re.I):
+                raise CX(_("invalid sector size (%s)" % t))
+
+        #if len(self.virt_path.split(',')) != len(tokens):
+        #    raise CX("number of sector items doesn't match number of virt path items")
+    self.virt_disk_sectors = vals
+    return True
+
 def set_virt_auto_boot(self,num):
     """
     For Virt only.
@@ -1459,6 +1474,26 @@ def set_virt_auto_boot(self,num):
         raise CX(_("invalid virt_auto_boot value (%s): value must be either '0' (disabled) or '1' (enabled)" % num))
     return True
 
+def set_virt_uefi_boot(self,num):
+    """
+    For Virt only.
+    """
+
+    if num == "<<inherit>>":
+        self.virt_auto_boot = "<<inherit>>"
+        return True
+
+    # num is a non-negative integer (0 means default)
+    try:
+        inum = int(num)
+        if (inum == 0) or (inum == 1):
+            self.virt_uefi_boot = inum
+            return True
+        raise CX(_("invalid virt_uefi_boot value (%s): value must be either '0' (disabled) or '1' (enabled)" % inum))
+    except:
+        raise CX(_("invalid virt_uefi_boot value (%s): value must be either '0' (disabled) or '1' (enabled)" % num))
+    return True
+
 def set_virt_pxe_boot(self,num):
     """
     For Virt only.

From 9b4c9fa213d6775d7624dfa9fb24d579a1fcc2e2 Mon Sep 17 00:00:00 2001
From: Yuri A <yuri@theta.local>
Date: Fri, 16 Jun 2017 09:51:54 -0400
Subject: [PATCH 3/4] koan: check virt-install for sectors support before
 trying to pass the option

---
 koan/app.py         | 5 ++++-
 koan/virtinstall.py | 7 ++++++-
 2 files changed, 10 insertions(+), 2 deletions(-)

diff --git a/koan/app.py b/koan/app.py
index f122438f6..c42fc1aac 100755
--- a/koan/app.py
+++ b/koan/app.py
@@ -1654,7 +1654,10 @@ def merge_disk_data(self, paths, sizes, drivers, sectors):
                 driver = drivers[-1]
             else:
                 driver = drivers[counter]
-            sector_size = sectors[counter]
+            if counter >= len(sectors): 
+                sector_size = sectors[-1]
+            else:
+                sector_size = sectors[counter]
             disks.append([path,size,driver,sector_size])
             counter = counter + 1
         if len(disks) == 0:
diff --git a/koan/virtinstall.py b/koan/virtinstall.py
index 6aebaa01d..c1ef4c4df 100644
--- a/koan/virtinstall.py
+++ b/koan/virtinstall.py
@@ -89,6 +89,11 @@
             # okay, probably on old os and we'll just use generic26
             pass
 
+sectors_supported = False
+rc, response = utils.subprocess_get_response(
+    shlex.split('virt-install --disk=? | grep -q logical_block_size'), True)
+if rc == 0:
+    sectors_supported = True
 
 def _sanitize_disks(disks):
     ret = []
@@ -421,7 +426,7 @@ def build_commandline(uri,
             cmd += ",bus=%s" % disk_bus
         if driver_type and not disable_driver_type:
             cmd += ",format=%s" % driver_type
-	if sector_size and StrictVersion(virtinst_version) >= StrictVersion('1.4.0'):
+	if sectors_supported and sector_size and StrictVersion(virtinst_version) >= StrictVersion('1.4.0'):
 	    lbs, pbs = {		
                 '4kn':  (4096, 4096),
                 '512e': (512, 4096),

From 5d7aadba751d64926574f911cc66b706a0e5f495 Mon Sep 17 00:00:00 2001
From: Yuri A <yuri@theta.local>
Date: Wed, 30 Aug 2017 16:28:36 -0400
Subject: [PATCH 4/4] koan: fix virt-install sector size check

---
 koan/virtinstall.py | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)

diff --git a/koan/virtinstall.py b/koan/virtinstall.py
index c1ef4c4df..367e1d0ea 100644
--- a/koan/virtinstall.py
+++ b/koan/virtinstall.py
@@ -91,8 +91,8 @@
 
 sectors_supported = False
 rc, response = utils.subprocess_get_response(
-    shlex.split('virt-install --disk=? | grep -q logical_block_size'), True)
-if rc == 0:
+    shlex.split('virt-install --disk=?'), True)
+if rc == 0 and 'logical_block_size' in response:
     sectors_supported = True
 
 def _sanitize_disks(disks):

```

**Comment by SchoolGuy** [comment] 2020-09-25 09:25
The patch is targeted for Release 2.8.x so this needs to be adjusted and split because Koan is now a separate Repo.

**Comment by dansou901** [comment] 2020-09-25 13:53
Just to document what I have done to make uefi pxe boot work via grub:
1. Installed grub2-x64-efi-modules as dependency for the mkgrub.sh script (for x64 efi targets, for other targets you will need to install other packages)
2. Created a bootable grubx64.efi loader via /usr/share/cobbler/bin/mkgrub.sh
3. copied that loader to tftp root folder
4. in /etc/cobbler/settings grubconfig_dir has to be set to /var/lib/cobbler/grub_config
5. cobbler sync automatically populates the grub configuration directory now in tftp root folder
6. In your dhcp server, point option 67 (filename) to grubx64.efi (assuming you have configured the other options already)

I'm not entirely sure if that gets done automatically, but the generated grubx64.efi in /var/lib/cobbler/loaders should get copied to the tftp root folder by cobbler sync as well. Please correct me if I'm wrong.

When you want to use cloud init with the new subiquity installer in Ubuntu 20.04, please keep in mind that the nocloud source has to be quoted in grub, otherwise it won't work. For syslinux however, the nocloud source mustn't be quoted! That said, currently you can't use cloud init profiles for Ubuntu 20.04 simultaneously in both syslinux and grub.

**Comment by SchoolGuy** [comment] 2020-10-02 15:36
So update on my progress with this so far:

- I manged create a testsetup with sumaform (which means I have a modified Cobbler 3.1.2 from SUMA)
- I have found a bug when using ``--standalone --distro``. If it's not a bug the error message is not understandable and thus we need to improve this behavior.

**Comment by SchoolGuy** [comment] 2020-10-02 16:02
Okay the bug was fixed in my pr with the commit bf23e45

**Comment by oliver-yu** [comment] 2021-06-14 17:36
请大神们撸起袖子加油干，把ESXI UEFI模式启动的问题搞定一下，我熬夜了几晚上测试UEFI模式安装不成功。

**Comment by SchoolGuy** [comment] 2021-06-15 06:17
@oliver-yu I hope that Google Translate was correct with the translation of Chinese but if it was, you may find the WIP PR here: https://github.com/cobbler/cobbler/pull/2416

Approximately by the end of the week or end of next week I will get this merged hopefully and then I will stabalize the current `master` branch, so we can get the new release out soon. But since this project has currently two developers, everything takes a while until it is done.

**Closed** 2021-12-15 13:57 UTC
Labels: Feature Request, ISO, PXE, tech-debt
