### ISSUE TITLE
bug with --power-pass with string manipulation

### ISSUE THREAD

**Issue by shahzebsiddiqui** [cobbler/cobbler#2231] opened 2020-01-07 15:13 UTC
### issue when passing power password that includes exclamation point ! and probably true with other special characters

Issue can be resolved using single quotes

This is applicable for version `2.8.5`

Here is a sample password entry that failed
```
[root@cherrysim ~]# cobbler system edit --name=declinesim --power-type=ipmilan --power-address=ilo-declinesim.dsone.3ds.com --power-user="root" --power-pass="badpass!xdsds"                                                   
-bash: !xdsds": event not found
```

```
[root@cherrysim ~]# cobbler system edit --name=declinesim --power-type=ipmilan --power-address=ilo-declinesim.dsone.3ds.com --power-user="root" --power-pass='badpass!xdsds'
[root@cherrysim ~]# cobbler system report | grep Password
Power Management Password      : badpass!xdsds
```

If i try with single quotes it works. This issue also happens if you dont specify quotes in the password so I think this is a bug in way cobbler handles the argument type.

To demonstrate here is the same command without quotes
```
[root@cherrysim ~]# cobbler system edit --name=declinesim --power-type=ipmilan --power-address=ilo-declinesim.dsone.3ds.com --power-user="root" --power-pass=badpass!xdsds
-bash: !xdsds: event not found

```

**Comment by xenlo** [comment] 2020-01-07 16:01
Not a bug!

The `!` is interpreted by bash before running the cobbler command. It's how bash behave.

**Comment by SchoolGuy** [comment] 2020-01-07 17:02
Still we should try to document it so users know it's not a bug. @xenlo

**Comment by watologo1** [comment] 2020-01-09 06:22
I have to agree with @xenlo and this does not need documentation (at least not in cobbler).

Bad:
--power-pass="badpass!xdsds"
also bad:
--power-pass="bad${Pass}xdsds"
or intended if you want to paste $Pass variable as part of the password.

I close this one, we have enough other issues...

**Closed by watologo1** 2020-01-09 06:22 UTC
Labels: Bug Report
