### ISSUE TITLE
Cobbler Import fails

### ISSUE THREAD

**Issue by zjf199249** [cobbler/cobbler#3565] opened 2024-01-26 10:37 UTC
### Describe the bug
```
root@kwai:/mnt# cobbler import --path=/mnt --name=Centos-7 --arch=x86_64
task started: 2024-01-26_100828_Media import_b936831f17a1443ea10d82ad70633229
task started (id=Media import, time=Fri Jan 26 10:08:28 2024)
start_task(import); event_id(2024-01-26_100828_Media import_b936831f17a1443ea10d82ad70633229)
import_tree; ['/mnt', 'Centos-7', None, None, None]
importing from a network location, running rsync to fetch the files first
running: ['rsync', '--archive', '--progress', '/mnt/', '/var/www/cobbler/distro_mirror/Centos-7-x86_64']
received on stdout: sending incremental file list
Exception occurred: <class 'ImportError'>
Exception value: Could not retrieve import signatures module!
Exception Info:
!!! TASK FAILED !!!
```

signature reload error

```
root@kwai:/mnt# cobbler signature reload
There was an error loading the signature data in .
Please check the JSON file or run 'cobbler signature update'.
root@kwai:/mnt# cobbler signature update
task started: 2024-01-26_102441_Updating Signatures_b5749ccde3bf4d6b8b894e51713d3fe8
task started (id=Updating Signatures, time=Fri Jan 26 10:24:41 2024)
start_task(sigupdate); event_id(2024-01-26_102441_Updating Signatures_b5749ccde3bf4d6b8b894e51713d3fe8)
*** TASK COMPLETE ***
root@kwai:/mnt# cobbler signature reload
There was an error loading the signature data in .
Please check the JSON file or run 'cobbler signature update'.
```

### Steps to reproduce

1. None given

### Cobbler version

```
root@kwai:/var/www/cobbler/distro_mirror# cobbler --version
Cobbler 3.4.0
  source: 67d05ce5, Tue Sep 19 13:09:43 2023 +0200
  build time: Fri Jan 26 09:33:16 2024
```

### Operating system

```
root@kwai:/var/www/cobbler/distro_mirror# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy
```

### Cobbler log

````paste below
````

**Comment by zjf199249** [comment] 2024-01-30 10:51
Do you guys have a solution

**Comment by SchoolGuy** [comment] 2024-01-30 10:58
So far I did not have the time to look into this specific bug. So far what I can see is that the filename parameter in the error message seems to be empty. This shouldn't be possible with the given command since the default file (in case no argument is given) is `/var/lib/cobbler/distro_signatures.json`.

**Comment by zjf199249** [comment] 2024-01-31 01:43
The approximate meaning is that the cobler did not recognize this file/var/lib/cobbler/distro_ Signatures.json

> 到目前为止，我没有时间研究这个特定的错误。到目前为止，我可以看到错误消息中的文件名参数似乎是空的。使用给定的命令，这应该是不可能的，因为默认文件（如果没有给出参数）是 .`/var/lib/cobbler/distro_signatures.json`

**Comment by zjf199249** [comment] 2024-01-31 01:44
The approximate meaning is that the cobler did not recognize this file/var/lib/cobbler/distro_ Signatures.json




> So far I did not have the time to look into this specific bug. So far what I can see is that the filename parameter in the error message seems to be empty. This shouldn't be possible with the given command since the default file (in case no argument is given) is `/var/lib/cobbler/distro_signatures.json`.

**Comment by zjf199249** [comment] 2024-01-31 01:45
> So far I did not have the time to look into this specific bug. So far what I can see is that the filename parameter in the error message seems to be empty. This shouldn't be possible with the given command since the default file (in case no argument is given) is `/var/lib/cobbler/distro_signatures.json`.

The approximate meaning is that the cobbler did not recognize this file /var/lib/cobbler/distro_ Signatures.json

**Comment by SchoolGuy** [comment] 2024-01-31 13:12
I will try to reproduce this at work as soon as I can.

**Comment by zjf199249** [comment] 2024-02-01 02:52
> I will try to reproduce this at work as soon as I can.

Also, I tried 3.3.3 and it's the same. The error in 3.3.2 is different
root@kwai:/mnt# cobbler import --name=Centos7 --arch=x86_64 --path=/mnt
task started: 2024-02-01_023023_import
task started (id=Media import, time=Thu Feb  1 02:30:23 2024)
running python triggers from /var/lib/cobbler/triggers/task/import/pre/*
running shell triggers from /var/lib/cobbler/triggers/task/import/pre/*
shell triggers finished successfully
import_tree; ['/mnt', 'Centos7', None, None, None]
importing from a network location, running rsync to fetch the files first
running: rsync -a  '/mnt/' /var/www/cobbler/distro_mirror/Centos7-x86_64 --progress
received on stdout: sending incremental file list
received on stderr: 
Exception occurred: <class 'AttributeError'>
Exception value: 'NoneType' object has no attribute 'get_import_manager'
Exception Info:
!!! TASK FAILED !!!

**Comment by SchoolGuy** [comment] 2024-02-01 08:34
Is this matter resolved or do you require further assistance?

**Comment by zjf199249** [comment] 2024-02-01 08:37
> Is this matter resolved or do you require further assistance in it?

Yes, it has been resolved, but when a new problem arises and starts
![1706776580678](https://github.com/cobbler/cobbler/assets/100892846/965338b6-17ed-422f-b618-6ef128ac8247)

**Comment by SchoolGuy** [comment] 2024-02-01 08:42
Mere seconds before you see this screen you might see an error message. If yes it would be nice to know what it says.

In any case it would be nice to see the output the following commands executed in this prompt:

```
net_ls_addr
net_ls_routes
echo $prefix
```

This will show if GRUB got an IP address if the routes are set correctly, and what the current prefix is. Furthermore, you might want to check on the server side what files the client requested.

**Comment by zjf199249** [comment] 2024-02-01 08:48
Everything seems normal

![Uploading 1706776580678.png…]()

**Comment by zjf199249** [comment] 2024-02-01 08:48
> Mere seconds before you see this screen you might see an error message. If yes it would be nice to know what it says.
> 
> In any case it would be nice to see the output the following commands executed in this prompt:
> 
> ```
> net_ls_addr
> net_ls_routes
> echo $prefix
> ```
> 
> This will show if GRUB got an IP address if the routes are set correctly, and what the current prefix is. Furthermore, you might want to check on the server side what files the client requested.

Everything seems normal

![Uploading 1706776580678.png…]()

**Comment by zjf199249** [comment] 2024-02-01 08:49
![Uploading 1706776580678.png…]()

**Comment by SchoolGuy** [comment] 2024-02-01 08:53
Sadly the upload didn't work as expected. Could you try again please?

**Comment by zjf199249** [comment] 2024-02-01 08:54
> Sadly the upload didn't work as expected. Could you try again please?

![1706776580678](https://github.com/cobbler/cobbler/assets/100892846/24451c36-164b-4da8-ab8a-663bc3c40039)

**Comment by SchoolGuy** [comment] 2024-02-01 08:58
Okay that looks indeed correct. Now I have a couple more questions:

1. Is this a virtualized setup or a bare metal one?
2. If bare metal: What CPU is this?
3. What is your "normal" boot order?

**Comment by zjf199249** [comment] 2024-02-01 09:00
> Okay that looks indeed correct. Now I have a couple more questions:
> 
> 1. Is this a virtualized setup or a bare metal one?
> 2. If bare metal: What CPU is this?
> 3. What is your "normal" boot order?

virtualization

**Comment by zjf199249** [comment] 2024-02-01 09:05
I saw the same problem here as me

https://github.com/orgs/cobbler/projects/2/views/3?pane=issue&itemId=22526946
![1706778326098](https://github.com/cobbler/cobbler/assets/100892846/61e825ad-a117-4710-bc5c-2f59ad28a7b8)

**Comment by zjf199249** [comment] 2024-02-01 09:33
> Okay that looks indeed correct. Now I have a couple more questions:
> 
> 1. Is this a virtualized setup or a bare metal one?
> 2. If bare metal: What CPU is this?
> 3. What is your "normal" boot order?

I found that the computer cannot succeed in bioot mode, but it can in uefi mode

**Comment by SchoolGuy** [comment] 2024-02-01 09:44
Perfect. Then I will close this issue as completed now.

**Closed by SchoolGuy** 2024-02-01 09:44 UTC
Labels: Bug Report, main, host-os/ubuntu/22
