### ISSUE TITLE
Get `Internal Server Error` when accessing `/cblr/svc/`

### ISSUE THREAD

**Issue by wy-z** [cobbler/cobbler#3016] opened 2022-04-02 06:51 UTC
### Describe the bug

Get `Internal Server Error` when accessing `/cblr/svc/`.

<img width="601" alt="image" src="https://user-images.githubusercontent.com/4213483/161369762-fe7daead-44f2-42f2-992b-e4911e39fdb1.png">

### Steps to reproduce

1. Install Cobbler v3.3.2
2. Request `http://127.0.0.1/cblr/svc/`

### Expected behavior

Return `200 OK`.

### Cobbler version

````
Cobbler 3.3.2
  source: ?, ?
  build time: Wed Mar 16 02:41:51 2022
````

### Operating system

```
NAME="Rocky Linux"
VERSION="8.4 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel fedora"
VERSION_ID="8.4"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.4 (Green Obsidian)"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:rocky:rocky:8.4:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
ROCKY_SUPPORT_PRODUCT="Rocky Linux"
ROCKY_SUPPORT_PRODUCT_VERSION="8"
```

### Cobbler log

````
[Sat Apr 02 06:20:13.932783 2022] [wsgi:error] [pid 554:tid 132089670760192] [client 127.0.0.1:34680] mod_wsgi (pid=554): Exception occurred processing WSGI script '/var/www/cobbler/svc/services.py'.
[Sat Apr 02 06:20:13.934019 2022] [wsgi:error] [pid 554:tid 132089670760192] [client 127.0.0.1:34680] Traceback (most recent call last):
[Sat Apr 02 06:20:13.934071 2022] [wsgi:error] [pid 554:tid 132089670760192] [client 127.0.0.1:34680]   File "/var/www/cobbler/svc/services.py", line 89, in application
[Sat Apr 02 06:20:13.934075 2022] [wsgi:error] [pid 554:tid 132089670760192] [client 127.0.0.1:34680]     cw = CobblerSvc(server="http://127.0.0.1:%s" % remote_port)
[Sat Apr 02 06:20:13.934081 2022] [wsgi:error] [pid 554:tid 132089670760192] [client 127.0.0.1:34680]   File "/usr/lib/python3.6/site-packages/cobbler/services.py", line 51, in __init__
[Sat Apr 02 06:20:13.934084 2022] [wsgi:error] [pid 554:tid 132089670760192] [client 127.0.0.1:34680]     self.api = CobblerAPI()
[Sat Apr 02 06:20:13.934089 2022] [wsgi:error] [pid 554:tid 132089670760192] [client 127.0.0.1:34680]   File "/usr/lib/python3.6/site-packages/cobbler/api.py", line 91, in __init__
[Sat Apr 02 06:20:13.934092 2022] [wsgi:error] [pid 554:tid 132089670760192] [client 127.0.0.1:34680]     execute_settings_automigration)
[Sat Apr 02 06:20:13.934096 2022] [wsgi:error] [pid 554:tid 132089670760192] [client 127.0.0.1:34680]   File "/usr/lib/python3.6/site-packages/cobbler/api.py", line 156, in __generate_settings
[Sat Apr 02 06:20:13.934099 2022] [wsgi:error] [pid 554:tid 132089670760192] [client 127.0.0.1:34680]     new_settings.save(settings_path)
[Sat Apr 02 06:20:13.934103 2022] [wsgi:error] [pid 554:tid 132089670760192] [client 127.0.0.1:34680]   File "/usr/lib/python3.6/site-packages/cobbler/settings/__init__.py", line 267, in save
[Sat Apr 02 06:20:13.934108 2022] [wsgi:error] [pid 554:tid 132089670760192] [client 127.0.0.1:34680]     update_settings_file(self.to_dict(), filepath)
[Sat Apr 02 06:20:13.934115 2022] [wsgi:error] [pid 554:tid 132089670760192] [client 127.0.0.1:34680]   File "/usr/lib/python3.6/site-packages/cobbler/settings/__init__.py", line 356, in update_settings_file
[Sat Apr 02 06:20:13.934118 2022] [wsgi:error] [pid 554:tid 132089670760192] [client 127.0.0.1:34680]     shutil.copy(path, path.parent.joinpath(f"{path.stem}_{timestamp}{path.suffix}"))
[Sat Apr 02 06:20:13.934123 2022] [wsgi:error] [pid 554:tid 132089670760192] [client 127.0.0.1:34680]   File "/usr/lib64/python3.6/shutil.py", line 245, in copy
[Sat Apr 02 06:20:13.934126 2022] [wsgi:error] [pid 554:tid 132089670760192] [client 127.0.0.1:34680]     copyfile(src, dst, follow_symlinks=follow_symlinks)
[Sat Apr 02 06:20:13.934130 2022] [wsgi:error] [pid 554:tid 132089670760192] [client 127.0.0.1:34680]   File "/usr/lib64/python3.6/shutil.py", line 121, in copyfile
[Sat Apr 02 06:20:13.934133 2022] [wsgi:error] [pid 554:tid 132089670760192] [client 127.0.0.1:34680]     with open(dst, 'wb') as fdst:
[Sat Apr 02 06:20:13.934147 2022] [wsgi:error] [pid 554:tid 132089670760192] [client 127.0.0.1:34680] PermissionError: [Errno 13] Permission denied: '/etc/cobbler/settings_20220402_06-20-13.yaml'
````

### Screenshots

![image](https://user-images.githubusercontent.com/4213483/161369778-2564f980-be72-424b-9322-b6e24ae779c8.png)

### Additional information

This should be a file permission issue for the `apache` user.
It worked fine after I changed the permission of `/etc/cobbler, /etc/cobbler/settings.yaml, /etc/cobbler/modules.conf`.
```sh
chmod g+rw /etc/cobbler /etc/cobbler/settings.yaml /etc/cobbler/modules.conf
usermod -aG root apache
systemctl restart httpd
```

**Comment by wy-z** [comment] 2022-04-02 06:54
Hi, @SchoolGuy 
This may be a bug for `3.3.2`, hope it helps.

**Comment by SchoolGuy** [comment] 2022-04-04 06:21
@wy-z I am aware of it. The reason for this are the following two PRs which were not properly tested in regard to the HTTP API (we don't have tests for that sadly atm):

- https://github.com/cobbler/cobbler/pull/2945
- https://github.com/cobbler/cobbler/pull/2946

The workaround is to revert the permissions to the old state and make the files world readable. I am working on a solution in the meantime.

**Comment by SchoolGuy** [comment] 2022-04-06 08:27
Closing this as a duplicate of https://github.com/cobbler/cobbler/issues/2967

**Closed by SchoolGuy** 2022-04-06 08:27 UTC
Labels: Bug Report

**Comment by marbaa** [comment] 2022-10-30 18:23
Just adding my observation to this ERROR 500.

I made two VM's. Version ```3.2.2``` and version ```3.3.2```. Until I fount this github issue, I compared a lot of files. Both versions have almost same file permissions for ```/etc/cobbler /etc/cobbler/settings.yaml /etc/cobbler/modules.conf```

**3.2.2**
```
# cobbler --version
Cobbler 3.2.2
  source: ?, ?
  build time: Fri Aug 26 01:42:52 2022
[root@home-cobbler cobbler]# ls -ld /etc/cobbler/
drwxr-xr-x 7 root root 4096 Oct 30 18:45 /etc/cobbler/

[root@home-cobbler cobbler]# ls -l /etc/cobbler/settings.yaml /etc/cobbler/modules.conf
-rw------- 1 root root    3642 Sep 21  2021 /etc/cobbler/modules.conf
-rw-r----- 1 root apache 20319 Oct 15 19:29 /etc/cobbler/settings.yaml
[root@home-cobbler cobbler]# id apache
uid=48(apache) gid=48(apache) groups=48(apache)
[root@home-cobbler cobbler]#
```

**3.3.2**
```
# cobbler --version
Cobbler 3.3.2
  source: ?, ?
  build time: Wed May  4 01:38:10 2022
[root@alma-dnsclient httpd]# ls -ld /etc/cobbler
drwx--xr-x 8 root root 4096 Oct 30 19:04 /etc/cobbler

[root@alma-dnsclient httpd]# ls -l /etc/cobbler/settings.yaml /etc/cobbler/modules.conf
-rw------- 1 root root    351 Mar 11  2022 /etc/cobbler/modules.conf
-rw------- 1 root apache 5271 Oct 30 19:04 /etc/cobbler/settings.yaml
[root@alma-dnsclient httpd]# id apache
uid=48(apache) gid=48(apache) groups=48(apache)
```

Are you sure only those two PR's are the cause of this bug?

 If I set same permissions according ```3.2.2```, it is still not working. It even doesn't work after setting same permissions as ```3.2.2``` **and** adding user apache to root group. It starts to work if you set more broader (needed writable permission) permissions than they were in ```3.2.2``` **and** add user apache to root group that wasn't there before.

**Comment by SchoolGuy** [comment] 2022-11-16 20:50
@marbaa Yes I am sure that these are the root case. The reason why you need to broaden the privileges so wide is because the class `CobblerAPI` requires write permission on those files. Since the `mod_wsgi` script is using just mentioned class the Apache user requires to be added as you just described.
