### ISSUE TITLE
Cobbler import Fedora 23 workstation "Task Failed"

### ISSUE THREAD

**Issue by chinaskyy** [cobbler/cobbler#1713] opened 2016-10-21 08:54 UTC
I try to import Fedora 23 workstation in cobbler (http://ftp.ciril.fr/pub/linux/fedora/linux/releases/23/Workstation/x86_64/iso/Fedora-Live-Workstation-x86_64-23-10.iso) 

Version cobbler : cobbler-2.6.11-4.fc24.x86_64

Step1 update signature : 
cobbler signature update
task started: 2016-10-21_105259_sigupdate
task started (id=Updating Signatures, time=Fri Oct 21 10:52:59 2016)
Successfully got file from http://cobbler.github.io/signatures/2.6.x/latest.json
**\* TASK COMPLETE ***

Step2 import fedora23

cobbler import --name=fedora23 --arch=x86_64 --path=/mnt
task started: 2016-10-21_105102_import
task started (id=Media import, time=Fri Oct 21 10:51:02 2016)
No signature matched in /var/www/cobbler/ks_mirror/fedora23-x86_64
!!! TASK FAILED !!!

Any Idea ?

**Comment by jmaas** [comment] 2016-10-22 05:19
I think only the server iso is supported, i've never tried the workstation iso.

**Comment by jmaas** [comment] 2016-11-27 15:29
I've verified it, only the server ISO is supported by the signatures.
This is not a bug, closing.

**Closed by jmaas** 2016-11-27 15:29 UTC
