### ISSUE TITLE
/etc/xinetd.d/rsync does not exist on centos6.7 x86_64

### ISSUE THREAD

**Issue by robbenwang** [cobbler/cobbler#1651] opened 2016-04-08 09:07 UTC
I am on CentOS 6.7 x86_64 with cobbler-2.6.11  , 
" cobbler check"  report /etc/xinetd.d/rsync not found,but the file is exist.
```
# cobbler check
The following are potential configuration items that you may want to fix:

1 : file /etc/xinetd.d/rsync does not exist

Restart cobblerd and then run 'cobbler sync' to apply changes.

# ll /etc/xinetd.d/rsync
-rw-r--r-- 1 root root 331 Apr  8 15:57 /etc/xinetd.d/rsyn
# rpm -qa | grep ^cobbler
cobbler-2.6.11-1.el6.x86_64
cobbler-web-2.6.11-1.el6.noarch
```

**Comment by nacc** [comment] 2016-04-11 21:54
It's unclear from your report, but the file listing provided is for "/etc/xinet.d/rsyn"? Is that just a typo?

**Comment by robbenwang** [comment] 2016-04-12 02:56
yes ,it is a typo 
# ll /etc/xinetd.d/rsync
-rw-r--r-- 1 root root 331 Apr  8 15:57 /etc/xinetd.d/rsync

**Comment by nacc** [comment] 2016-04-12 17:04
2.6.11 requires (it seems) systemd:

        if not os.path.exists("/usr/lib/systemd") and os.path.exists("/etc/xinetd.d"):

Are both those true on your system?

**Comment by tmblue** [comment] 2016-04-27 05:52
CentOS release 6.7 (Final)

/etc/xinet.d/rsync exists, but what is that other path? One would think it would be /usr/lib64/ if that file even existed on CentOS (I don't think it does). I think this needs some adjustment..

**Comment by nacc** [comment] 2016-04-27 21:59
Depends on your distribution, modern 64-bit distributions use /usr/lib. 

Sounds like there might need to be some packaging adjustments to the centos package. I would file a bug with them?

**Comment by opoplawski** [comment] 2016-04-29 03:57
systemd  always installs its support files into /usr/lib/systemd - there are arch-independent files not binaries.

But the test is obviously incorrect - caused by https://github.com/cobbler/cobbler/commit/370f635fe94556a480264125a188eafc6faf4a73

**Comment by jmaas** [comment] 2016-05-10 04:28
Fixes have been merged, thanks @opoplawski

**Closed by jmaas** 2016-05-10 04:28 UTC
